### ISSUE TITLE
[BUG] Profile Page exposes email address

### ISSUE THREAD

**Issue by anoopmsivadas** [fossunited/fossunited#158]
### Describe the bug

The system currently identifies a  user using their  email address, and visibility of edit options are decided by checking `frappe.session.user` param. I assume its auto generated. But it exposes the email address in user profile page source. You don't even have to login to find the email address of the profile owner.

### Expected behavior

Since the email id is not visible in the profile, it should not be used there in the page source also. At least the user should have control over its visibility.

### To Reproduce

open a profile page from the platform in private(incognito) window. open the page source and search for  `frappe.session.user`

### Screenshots

![Screenshot from 2024-02-27 23-41-27-1](https://github.com/fossunited/fossunited/assets/46913894/105afd8d-b771-48b4-837d-22388b1a1ecc)

### Environment

```markdown
- Device:
- OS:
- Browser:
```

**Comment by harshtandiya** [comment]
Thank you for the bug report anoop! this was huge!
