### ISSUE TITLE
Profile Banner is not loading

### ISSUE THREAD

**Issue by DarkPhoenix2704** [fossunited/fossunited#163]
### Describe the bug

![image](https://github.com/fossunited/fossunited/assets/64391274/7999ae05-675a-46f6-8253-404a91944e06)

No Banner is shown in public when profile banner is set to private

### Expected behavior

When Profile banner is set to private, it should load default banner. 

### Environment

```markdown
- Device:
- OS:
- Browser:
```

**Comment by harshtandiya** [comment]
Oh no, my bad. The users aren't supposed to be having an option to keep it private. Fixing it!

**Comment by DarkPhoenix2704** [comment]
Please include an option to remove the user selected banner and revert to original one
