### ISSUE TITLE
[BUG] Edit Profile page is not properly responsive

### ISSUE THREAD

**Issue by sayakongit** [fossunited/fossunited#164]
### Describe the bug

The edit profile page is not properly responsive to mobile devices.

### Expected behavior

The form fields should have been aligned columned wise. Mainly the 'About' rich text box.

### To Reproduce

Devices with screen width <768px shall face this issue on 'Edit profile' page.

### Screenshots

![Screenshot 2024-03-01 223929](https://github.com/fossunited/fossunited/assets/83216382/bef3a2fd-d277-4909-920e-ea455f501743)

### Environment

```markdown
- Device: Mobile (width<768px)
- OS:
- Browser:
```

**Comment by sayakongit** [comment]
Assign this issue to me. I would like to work on this.

**Comment by harshtandiya** [comment]
Reload the page after clicking on responsive screen button. 

It works fine on smaller devices. 

![Screenshot_20240301_225031_Chrome](https://github.com/fossunited/fossunited/assets/73123690/8d7136ab-8d36-47c8-924b-5f3aebdcd599)

**Comment by sayakongit** [comment]
Okay got it. Thanks
