### ISSUE TITLE
Cleanup

### ISSUE THREAD

**Issue by NagariaHussain** [fossunited/fossunited#196]
### Issue description

- [x] Remove `Hackathons` module def
- [x] Make all doctype names singular, wherever necessary
- [x] Move to tailwind (https://youtu.be/pvJMIOkU3CI)
- [x] Simple Icons is 2MB! 

   ![CleanShot 2024-03-17 at 14 39 30@2x](https://github.com/fossunited/fossunited/assets/34810212/464b38e0-b28f-48d2-ac18-ce0eeaf59d09)

- [x] Better handle URL inputs (use Data with `URL` option for validation)
   ![CleanShot 2024-03-17 at 14 40 47@2x](https://github.com/fossunited/fossunited/assets/34810212/d5cf84ed-480a-448b-91a2-74af12c9c391)
 
- [x] Redundant 
  ![CleanShot 2024-03-17 at 14 41 40@2x](https://github.com/fossunited/fossunited/assets/34810212/e0938ae8-bdcc-406e-9c11-aec5e8732cec)

- [x] #201
- [x] Full name should be title field

- [x] CFP Reviewer
  ![CleanShot 2024-03-17 at 14 50 02@2x](https://github.com/fossunited/fossunited/assets/34810212/90882e2f-d53b-4337-8bcb-16fc7a44a6eb)

**Comment by harshtandiya** [comment]
Seems like Hackathons Module was removed earlier itself, try migrating the site and check again?
