### ISSUE TITLE
[FEATURE] Calendar Integrations

### ISSUE THREAD

**Issue by ansharora28** [fossunited/fossunited#224]
### Feature description

Adding a .ics or gcal/ical integration to events and talk schedules

### Use case

 For the talks schedule, adding a .ics integration will help people directly add the talks to their calendar, view it offline, get reminders (maybe volunteers can also move these talks around depending on the schedule,delays etc.)

**Comment by abhayguptas** [comment]
Hi, So the end goal for this is generating a .ics file when someone RSVP for any event and giving the user a button to download that file, right?

**Comment by harshtandiya** [comment]
The goal is to generate and send the ics file in the notification email

**Comment by mngshm** [comment]
Closing this issue as #302 is a similar issue.
