### ISSUE TITLE
[FUP-9] Create RSVP feature for an event

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/fossunited#23]
<p>The RSVPs for an event are taken via a web form.</p>
<ul>
<li><p>[x] Add a bunch of options with fields - for the event admins to select what fields should in the form.</p></li>
<li><p>Custom forms for each event (check possibility with @NagariaHussain)</p></li>
<li><p>[x] RSVP confirmation emails (custom content additions) </p></li>
<li><p>[x] Close RSVP once it hits the maximum RSVP count</p></li>
</ul>

**Comment by harshtandiya** [comment]
#28 & #29
