### ISSUE TITLE
[BUG] Discourse login seems to be broken

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#275]
### Describe the bug

After the migration to the new platform, the Discourse login seems to be broken. I'm not sure if the migration is the cause because I don't remember the last time I logged out and tried logging back in.

### Expected behavior

I expected the page to redirect me to the forum after the credentials were authenticated but instead i get a 404

### To Reproduce

- If you are logged in, logout from the Forum
- load the forum from the link on fossunited.org landing page Call To Action button
- Try to login to Forum
- Provide login credentials on the login page

### Screenshots

![forum-login-broken](https://github.com/fossunited/fossunited/assets/1926457/536f153b-4cba-4f18-abb1-9dbc0b2cce04)

### Environment

```markdown
- Device: Desktop
- OS: Windows 11
- Browser: Chrome 124.0.6367.119
```

**Comment by NagariaHussain** [comment]
@harshtandiya is this fixed now?

**Comment by harshtandiya** [comment]
This is fixed now

**Comment by rahulporuri** [comment]
> This is fixed now

I can confirm that this is fixed now.

Can I ask why it was broken in the first place and what the fix was?
