### ISSUE TITLE
"Upcoming Events" button on Events page feels redundant

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#276]
### Issue description

The "Upcoming Events" button on the https://fossunited.org/events page points to https://platform.fossunited.org/events, which now redirects back to https://fossunited.org/events. This feels redundant and potentially confusing to users, who should simply scroll down

**Comment by RiyaMathew-11** [comment]
The hero button on the [Events Page](https://fossunited.org/events) now navigates to [events timeline](https://fossunited.org/events/timeline) page
