### ISSUE TITLE
[BUG] "View all Events" button on FOSS Events page is broken

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#277]
### Describe the bug

"View all Events" on the [FOSS Events](https://fossunited.org/events) page leads to a broken `https://fossunited.org/%7B%7B%20events_page_link%20%7D%7D` link

### To Reproduce

- Open https://fossunited.org/events
- Scroll down to "Upcoming Events" section
- Click on the "View all Events"

### Environment

```markdown
- Device: Desktop
- OS: Windows 11
- Browser: Chrome
```

**Comment by RiyaMathew-11** [comment]
Fixed with the merged PR today - #240 

There's an all-events page now that's linked to View all Events - https://fossunited.org/events/timeline
