### ISSUE TITLE
[BUG] "FOSS Communities near you" list is out-of-sync with Map

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#278]
### Describe the bug

The list of city communities in "FOSS Communities near you" on the [FOSS Communities](https://fossunited.org/city-communities) page is out-of-sync with the Map showing the geographic locations of the carious city communities across India.

### Screenshots

![Screenshot 2024-05-05 170735](https://github.com/fossunited/fossunited/assets/1926457/ec8e8aa4-fc8c-4075-b40f-20b54baaf51b)

### Environment

```markdown
- Device: Desktop
- OS: Windows 11
- Browser: Chrome
```

**Comment by RiyaMathew-11** [comment]
This map is actually an image representation. We can consider making it dynamic later on, as new cities get added-on. 

Hence closing this issue for now.

**Comment by rahulporuri** [comment]
for the record, replaced with #353
