### ISSUE TITLE
[BUG] Some city pages don't have the default banner

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#279]
### Describe the bug

When going through the city communities listed under [FOSS Communities](https://fossunited.org/city-communities), some of the city community pages have the default banner where as others dont.

### To Reproduce

- See default banner at https://fossunited.org/vadodara
- See "blank"(?) banner at https://fossunited.org/mangalore

### Screenshots

|Default banner|Blank banner|
|--|--|
|![Screenshot 2024-05-05 171300](https://github.com/fossunited/fossunited/assets/1926457/a105863a-28e7-4000-be23-b3f771bd2221)|![Screenshot 2024-05-05 171219](https://github.com/fossunited/fossunited/assets/1926457/0f3c13f0-fe10-4b64-8228-f14dc85a066d)|

### Environment

```markdown
- Device: Laptop
- OS: Windows 11
- Browser: Chrome
```

**Comment by harshtandiya** [comment]
It is actually a custom banner. Chapters are able to change their banners
