### ISSUE TITLE
"Join a Community" button on FOSS Communities page does nothing

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#280]
### Issue description

"Join a Community" button on [FOSS Communities](https://fossunited.org/city-communities) page seemingly does nothing. Clicking it just causes the page to refresh.

**Comment by RiyaMathew-11** [comment]
Fixed with a patch - where the button redirects to the communities list section. While we shall later create a workflow for the joining communities to follow for updates on events etc.

**Comment by rahulporuri** [comment]
> While we shall later create a workflow for the joining communities to follow for updates on events etc.

I don't fully understand what you mean. I'm not sure what the ideal/desired solution is here.

**Comment by RiyaMathew-11** [comment]
So I've changed `Join a Community` to `Explore Communities` - to make the CTA to scroll down to the list of communities to be seen. 

We will implement a `Follow for Updates` wrt a community later on - it will facilitate to join a particular community and receive notifications whenever in case of a new event or other updates.
