### ISSUE TITLE
[QUESTION] Active FOSS Clubs arent easily discoverable

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#281]
### Question or issue

[City communities](https://fossunited.org/city-communities) page clearly outlines the active cities whereas such information isnt available on the [Clubs](https://fossunited.org/clubs) page.

**Comment by harshtandiya** [comment]
I agree, will do something about it

**Comment by harshtandiya** [comment]
https://fossunited.org/clubs/list

I think this was added recently by team. There is also a CTA in clubs page, which redirects to this list page.

**Comment by rahulporuri** [comment]
The page was updated from the Frappe app - https://fossunited.org/clubs/list and can be closed now
