### ISSUE TITLE
CLN: Remove internal uses of "platform.fossunited.org"

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#282]
### Issue description

Now that the migration of the platform.fossunited.org to fossunited.org is complete, we should check and remove any internal uses of `platform.fossunited.org`. We don't want the existing `platform.fossunited.org` links to break but also want to remove any internal references to the "platform". 

### Steps to reproduce (if applicable)

- Open https://fossunited.org/indiafoss/2024
- Click on "Propose a Talk", which first takes you to https://platform.fossunited.org/events/indiafoss24/

### Additional context

A general code search of the codebase reveals the following - https://github.com/search?q=repo%3Afossunited%2Ffossunited%20%22platform.%22&type=code

**Comment by rahulporuri** [comment]
> Early Birds Ticket is live now. Get your tickets [here](https://platform.fossunited.org/indiafoss/buy-tickets).

See https://fossunited.org/events/indiafoss24. The link points to https://platform.fossunited.org/indiafoss/buy-tickets

**Comment by harshtandiya** [comment]
I agree these need to change, however, this can be a low priority. platform.fossunited.org will still point to fossunited.org, and any subsequent paths like platform.fossunited.org/<path> get converted to fossunited.com/path

**Comment by rahulporuri** [comment]
it looks like #352 makes a few of the changes needed to resolve this issue. right @harshtandiya ?

**Comment by harshtandiya** [comment]
Yup! forgot to link it @rahulporuri , closing this issue

**Comment by rahulporuri** [comment]
I'm still seeing a few places where platform.fossunited.org is first being loaded, which then redirects to the relevant fossunited.org page. This doesn't appear to be happening in the code so it might be happening via the Frappe App settings?

**Comment by RiyaMathew-11** [comment]
Probably yes, could be from the web pages built in desk. I will scan through all the desk pages to start with.

**Comment by RiyaMathew-11** [comment]
I've scanned through all the pages and found the link in home page landing section primary CTA button - https://fossunited.org

The URL value field was in desk - for easy updation and such, while the code of the template, styling etc is in written in repo. 

I've also scanned all the web templates but there seem to be no links attributing to our former site URL. 

@rahulporuri please let me know if it was just this one, or did you find something else. We could close this issue if nothing else ?
