### ISSUE TITLE
[QUESTION] Which is the "right" IndiaFOSS 2024 page?

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#283]
### Question or issue

- In the "Flagship Events" section of fossunited.org, IndiaFOSS points to https://fossunited.org/indiafoss/2024.
- In the ["Events"](https://fossunited.org/events) page, under "Upcoming Events", IndiaFOSS points to https://fossunited.org/events/indiafoss24

Which is the "right" IndiaFOSS 2024 page?

**Comment by harshtandiya** [comment]
The first one is a public web page custom made just for IndiaFOSS. Second one is from the template which was autogenerated, as IndiaFOSS is also published as an event in our system. Both are needed imo, but if the question is which one people should see is the first page.

If we want to hide the second one, I think we can do that.

**Comment by RiyaMathew-11** [comment]
@harshtandiya how shall we solve this ? - will hiding the page, actually hide CFP list page too ? 

I think we should implement the `Adding external events` to our event timeline feature, we had a discussion on this sometime ago. I feel then, we can then easily link an external website ( like IndiaFOSS main webpage) to the event card.

**Comment by harshtandiya** [comment]
Let's thing and figure out a way for future. For now, I think it is okay as it is. We can market the fossunited.org/indiafoss/2024 as the main page. Link the CFP portal through a button directly leading to [fossunited.org/events/indafoss24/cfp](https://fossunited.org/events/indiafoss24/cfp). I don't see any positives to unpublishing the event page right now

**Comment by RiyaMathew-11** [comment]
Yeah sure, we can check on that.

Not just from IndiaFOSS perspective. But this workflow I feel is needed - we partner with a lot of events, and we do put them in our timeline too. If we decide to partner with an event - say next month, this addition would be required. 

Change-wise I feel, these would come afaik: 

- Add extra fields to FOSS Chapter Event Doctype - like a checkpoint for an external event and others. 
     - If an external event, there won't be a need to link the chapter. 
- Alter the event card macro to use conditionally use data from these fields. 
- The event cards might need a slight alter in design too - like the one @wisharya proposed? - that higlights the city in a smaller way. 

I don't think anything else would break in my knowledge.

**Comment by harshtandiya** [comment]
@RiyaMathew-11 create an issue for the event card maybe. Other than that, i think this issue can be closed?

**Comment by RiyaMathew-11** [comment]
> create an issue for the event card maybe

Can you make it a bit more detailed please ? 

Should I create issue to redesign the event card or to have separate event cards for external events? #329 is already there for external events to be included in timeline

**Comment by RiyaMathew-11** [comment]
@harshtandiya can you check on this and please comment what could be done? I'll like to fix the case for external events in my next PR if that's okay, as it's loosely based on events' timeline too

**Comment by harshtandiya** [comment]
External events were added with #386 .
