### ISSUE TITLE
[BUG] Banner on IndiaFOSS24 page is from IndiaFOSS 2.0, not 3.0

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#284]
### Describe the bug

- Visit https://fossunited.org/events/indiafoss24 to see the banner
- See the IndiaFOSS 3.0 picture at https://fossunited.org/indiafoss/2024

**Comment by harshtandiya** [comment]
Changed it. But it seems to be low quality. @RiyaMathew-11 Can we get the original photos with better quality and replace the photo

**Comment by RiyaMathew-11** [comment]
I will check with Ajzal and the original pic.

**Comment by RiyaMathew-11** [comment]
Fixed the event banner - edit made in desk
https://fossunited.org/events/indiafoss24
