### ISSUE TITLE
[BUG] Website title is currently "FOSS United Platform"

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#285]
### Describe the bug

See title at fossunited.org

### Screenshots

<img width="764" alt="Screenshot 2024-05-05 174728" src="https://github.com/fossunited/fossunited/assets/1926457/f3090b60-448f-452d-b44e-2d7e6e809e6c">

**Comment by RiyaMathew-11** [comment]
![Screenshot 2024-05-14 at 12 41 20 AM](https://github.com/fossunited/fossunited/assets/60656677/caa56e6e-1075-45a0-ba69-6c510116d9db)

Changed the title of the homepage to `FOSS United Foundation` - is this one ok to go @rahulporuri ?

- This change is directly made from the [platform desk](https://fossunited.org/app/web-page/foss-united-platform).

**Comment by rahulporuri** [comment]
> Changed the title of the homepage to FOSS United Foundation - is this one ok to go @rahulporuri ?

Good to go! Closing the issue as completed!

> This change is directly made from the [platform desk](https://fossunited.org/app/web-page/foss-united-platform).

Thank you very much for this additional information @RiyaMathew-11 ! This is helpful to understand the separation of concerns between the code and the desk/UI
