### ISSUE TITLE
[BUG] 404 for "Apply Now" button on FOSS Hack 2024

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#287]
### To Reproduce

- Go to https://fossunited.org/fosshack/2024
- Scroll down to the "Host a Hackathon in your Region" section
- Click on the "Apply now" button
- which takes us to the 404 page https://fossunited.org/fosshack/2024/host/application

Note that the button shouldn't exist because we are past the deadline for applications (April 15 2024)

**Comment by RiyaMathew-11** [comment]
Seems like the CTA section wasn't updated when the call for localhosts was closed. 

Have removed the section - until we get a new CTA to be added - updated link: https://fossunited.org/fosshack/2024
