### ISSUE TITLE
[BUG] 404 for Industry Partners page

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#288]
### Describe the bug

The Industry Partners page doesn't seem to exist at the moment.

### To Reproduce

- Open fossunited.org
- Scroll down to "Industry Partnership"
- Click "View Current Partners"
- which goes to the non existent https://fossunited.org/partners

**Comment by RiyaMathew-11** [comment]
This is fixed with the merged PR today - #240 

https://fossunited.org/industry-partners - new industry partners page

**Comment by RiyaMathew-11** [comment]
This is fixed with the merged PR today - #240 

https://fossunited.org/industry-partners - new industry partners page

**Comment by rahulporuri** [comment]
@RiyaMathew-11 when did Ditto stop being a podcast partner?

**Comment by rahulporuri** [comment]
Also, I like "Current Partners (2024-25)". We mention who the past partners are in the slide deck so why not also mention it in the website. What do you think @RiyaMathew-11 @wisharya ?

**Comment by fossdot** [comment]
I think it's a good idea.

**Comment by RiyaMathew-11** [comment]
> @RiyaMathew-11 when did Ditto stop being a podcast partner?

Sorry, this was missed out - added it: https://fossunited.org/industry-partners

**Comment by RiyaMathew-11** [comment]
> mention who the past partners are in the slide deck so why not also mention it in the website. 

I agree. Had proposed it before, but then was said it wasn't necessary for now. I will add the section in separate PR, and create a separate issue for it.

**Comment by RiyaMathew-11** [comment]
Added a separate issue - #301. Closing this one.
