### ISSUE TITLE
[BUG] Issues with the "Newsletter" page

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#289]
### Describe the bug

- missing image
- misaligned "Connect with us" text and "Get in touch" button
- missing "Past Newsletters"

### Screenshots

![Screenshot 2024-05-05 175626](https://github.com/fossunited/fossunited/assets/1926457/81a42208-a1cb-4ccf-a907-e1bf2c98557d)

**Comment by harshtandiya** [comment]
Replaced with the old one for now. https://fossunited.org/newsletter

**Comment by rahulporuri** [comment]
> Replaced with the old one for now. https://fossunited.org/newsletter

Can we also create a new issue to fix the new newsletter webpage? Or do we want to abandon the new newsletter webpage and stick to the old one?
