### ISSUE TITLE
[BUG] Team page is missing information

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#291]
### Describe the bug

[Our Team](https://fossunited.org/team) page is missing information.

### Expected behavior

https://archive.fossunited.org/about might contain some outdated information but it contains relevant information that is missing from the new "Our Team" page.

**Comment by RiyaMathew-11** [comment]
The information about the goals and vision of FOSS United is updated in the [homepage](https://fossunited.org).

The team page is updated with essential info via #348. 

We could make a showcase for volunteers later on, with other updates to the team page. This is referenced in #318
