### ISSUE TITLE
[BUG] inter.css stylesheet mimetype is unsupported

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#293]
### Describe the bug

I'm seeing the following error on Chrome and Firefox when I load fossunited.org

> Refused to apply style from 'https://fossunited.org/files/website_theme/frappe/public/css/fonts/inter/inter.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.

> The resource from “https://fossunited.org/files/website_theme/frappe/public/css/fonts/inter/inter.css” was blocked due to MIME type (“text/html”) mismatch (X-Content-Type-Options: nosniff).

I don't have enough experience with web development to know if this is serious.

**Comment by harshtandiya** [comment]
@NagariaHussain Can you help with this

**Comment by NagariaHussain** [comment]
If it doesn't break anything, the warning can be ignored.

**Comment by rahulporuri** [comment]
> If it doesn't break anything, the warning can be ignored.

Honestly, I don't know what it is breaking because I don't know what it does 😅 We can definitely ignore the warning but I would love to know why the warning is being raised.

**Comment by NagariaHussain** [comment]
Basically it is related to a font we use (inter). @harshtandiya can you do a quick search and check where this is being loaded?

**Comment by harshtandiya** [comment]
Issue actually exists in old site as well. This is most probably a Frappe error @NagariaHussain 

![image](https://github.com/fossunited/fossunited/assets/73123690/b26bdbc8-e867-42fa-bfa0-2a4aa2944afb)

**Comment by rahulporuri** [comment]
> Issue actually exists in old site as well. This is most probably a Frappe error @NagariaHussain

Can we report it upstream and close it here in that case?

**Comment by rahulporuri** [comment]
@harshtandiya was this issue reported upstream? I still see the issue on the webpage so it's not clear to me how this issue is closed as "completed".
