### ISSUE TITLE
Two different logos of IndiaFOSS 2024

### ISSUE THREAD

**Issue by fossdot** [fossunited/fossunited#298]
### Issue description

Currently, we are using two different logos of IndiaFOSS:
1. On IF2024 website (old)
![Screenshot(54)](https://github.com/fossunited/fossunited/assets/25725389/0ca8c0f0-df05-4e26-87e7-fface7206abc)

2. On posters (which is actual)
![Screenshot(55)](https://github.com/fossunited/fossunited/assets/25725389/1eb18ef3-ca4d-4bea-b927-f024eb110215)

**Comment by RiyaMathew-11** [comment]
Changed to the new logo 

![Screenshot 2024-05-07 at 6 26 59 PM](https://github.com/fossunited/fossunited/assets/60656677/c1064c9d-c644-475f-a87e-fb93634275e4)

**Comment by rahulporuri** [comment]
@RiyaMathew-11 i don't know enough about the Frappe framework but I thought this fix would require a code change. But it looks like the change went through the Desk instead. Is that correct? Can this not be fixed in code?

**Comment by RiyaMathew-11** [comment]
No - the IndiaFOSS page itself is a page in the desk. So the edits in code were made in the desk.
