### ISSUE TITLE
[BUG] Cannot add or update details in FOSS profiles

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/fossunited#308]
### Describe the bug

Tried to test updating details in the `Experience` Section of FOSS Profiles - at the time of submission: gives the following error messgae: 

`'fossunited.org' is not a valid URL`

### Expected behavior

On submission, the entry ought to be updated in the profile page.

### Screenshots

![Screenshot 2024-05-11 at 12 41 36 AM](https://github.com/fossunited/fossunited/assets/60656677/cd65bc8a-43f8-4fb8-aec0-1700cf2dbcca)

<img width="800" alt="Screenshot 2024-05-11 at 12 42 34 AM" src="https://github.com/fossunited/fossunited/assets/60656677/b713dfa1-523a-4c09-8210-9609a75267a2">

**Comment by harshtandiya** [comment]
It's because your other experiences must not have a correct url. 

Company website is a URL field which validates URLs. So you will have to put the complete link with https:// so, `fossunited.org` -> `https://fossunited.org`

**Comment by harshtandiya** [comment]
I will create a workaround for this, since people who aren't desk users may not be able to fix it properly
