### ISSUE TITLE
[BUG] Lead a foss club button does not work.

### ISSUE THREAD

**Issue by adityacodes30** [fossunited/fossunited#310]
### Describe the bug

The lead a foss club button at  https://fossunited.org/clubs does not work. Is it disabled or a bug ?

**Comment by harshtandiya** [comment]
@RiyaMathew-11 it seems its a button when it's supposed to be an `<a>` tag? can you look and fix

**Comment by adityacodes30** [comment]
can you please point me to the correct link

**Comment by adityacodes30** [comment]
do you mind if i fix this one

**Comment by RiyaMathew-11** [comment]
My apologies for the late reply @adityacodes30. I have fixed it in my upcoming bug-fix PR - #348. 

The link was supposed to redirect to the [FOSS Club roadmap](https://forum.fossunited.org/t/foss-clubs-2024-roadmap/2601) post on forum which would later on have updates on the next cohort applications as well.
