### ISSUE TITLE
[DOCS] Documentation for city chapter volunteer onboarding

### ISSUE THREAD

**Issue by ansharora28** [fossunited/fossunited#311]
### Documentation request

- Using the Dashboard
- Creating events
- Handling RSVP/CFP 
..etc

**Comment by mngshm** [comment]
Hey, I'll take this task up.

**Comment by harshtandiya** [comment]
@Mangeshrex 

Use the Wiki installed on the site. 
Create a different space for these documentations than the current one.

**Comment by mngshm** [comment]
This is done, documentation is available on fossunited.org/manual. Closing the issue
