### ISSUE TITLE
[QUESTION] How to post May 2024 newsletter to blog

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#312]
### Question or issue

The May 2024 newsletter was just published and we need to post it to the blog as well. But it's not clear at the moment how to post a new blogpost on the blog.

**Comment by harshtandiya** [comment]
Hi Rahul,
Writing the steps below on how to for blogs

---

#### Steps for a FOSS United Team member to post a blog

 Only a person with a System User Role with "Blogger" Role profile will be able to access the website desk and post a blog. System User role is given to only a handful of people, currently only limited to people in FOSSU team and active tech volunteers such as Hussain.

#### **Steps to post a blog:**
1. **Switch to desk**
	You will find the "Switch to desk" button when you click on your profile photo in the website navbar. 
	![image](https://github.com/fossunited/fossunited/assets/73123690/8640d614-9709-406e-ae51-1a586b518283)
Or you can directly visit https://fossunited.org/app
2. **Switch to Blog Workspace**
	On accessing the desk, you should find a sidebar. Find the "Blog" section and click on it to get to the Blog Workspace
![image](https://github.com/fossunited/fossunited/assets/73123690/2682570b-66b3-41aa-a81c-c75e36ac6bcf)

3. **Create a Blog**
	This workspace will provide you with shortcuts to create a blog, view all blogs and view published blogs. The work from here is straightforward.
	![image](https://github.com/fossunited/fossunited/assets/73123690/198fb6a1-6bb5-4c5c-b9e0-b8257eead3a7)
4. Create Blog Form
	The form for Create a blog post looks something like this. We generally do not need to change anything, other than adding data of our own. The route is auto-generated AFAIK. And the blog can be published via the publish button AFTER it has been created. 	
![image](https://github.com/fossunited/fossunited/assets/73123690/e9d76a0c-d916-4998-9f95-02b13b3e00c1)
	If you do not find your name in the list of bloggers, by all means feel free to create a blogger instance of yourself by clicking on "Create a new blogger" as shown below.
	![image](https://github.com/fossunited/fossunited/assets/73123690/4b6b65fd-768f-496a-8c7a-740d098f72b5)
	Content Type can be either markdown, rich text or HTML which can be handy.
	![image](https://github.com/fossunited/fossunited/assets/73123690/f1784e12-ac18-4e6f-8cdb-465c5140797d)

**Comment by harshtandiya** [comment]
Closing this.

**Comment by rahulporuri** [comment]
Thanks for the documentation @harshtandiya . We'll try to move the information out of the GitHub issue comment and into something that can live longer e.g. a Google Doc or a Wiki page or something
