### ISSUE TITLE
[BUG] The footer seems to override the body on the `cfp/all` page (possibly others too)

### ISSUE THREAD

**Issue by Udayraj123** [fossunited/fossunited#316]
### Describe the bug

Sample link: https://fossunited.org/events/blr-may/cfp/all

The tiles on the bottom seem to get hidden, probably due to the body not using its own content height. This issue can be potentially more general than for this page alone.

### Expected behavior

The footer should not hide the main body. Currently it works by zooming out (Cmd -)
<img width="1189" alt="image" src="https://github.com/fossunited/fossunited/assets/16881051/efe6f9c6-444e-4284-9876-b9d5dfa1c95e">

### To Reproduce

1. Login and visit https://fossunited.org/events/blr-may/cfp/all
2. The issue should be visible. If not, try to set smaller device screen using the dev console

### Screenshots

<img width="1226" alt="image" src="https://github.com/fossunited/fossunited/assets/16881051/13d89ddb-59a6-42d8-b416-c760eddbba16">

### Environment

```markdown
- Device: Desktop
- OS: MacOS 14.4.11
- Browser: Google Chrome
```

**Comment by rahulporuri** [comment]
> The issue should be visible. If not, try to set smaller device screen using the dev console

I'm able to reproduce this on Windows + Firefox by shrinking the browser vertically until the proposals hide behind the footer.

Thanks for the clear report @Udayraj123 !

**Comment by rahulporuri** [comment]
@harshtandiya neat. I put the issues in the "In Progress" column of the project and GitHub automation kicked in to move them to the "Done" column after the issues were closed
