### ISSUE TITLE
[BUG] "Explore Communities" on FOSS City Communities does nothing

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#322]
### To Reproduce

* Visit https://fossunited.org/city-communities
* Click on the "Explore Communities" button

![city-comms-button](https://github.com/fossunited/fossunited/assets/1926457/e48d3cd0-8da8-4477-9982-584b2f967c2b)

### Environment

```markdown
- Device: Desktop
- OS: Windows 11
- Browser: Firefox
```

**Comment by RiyaMathew-11** [comment]
It should actually scroll down to the `FOSS Communities Near You` section.

I am not able to reproduce this on Chrome - as it works fine. 
![city-com-demo](https://github.com/fossunited/fossunited/assets/60656677/1b3dc6e5-3da0-49bb-80de-00c78110879d)

This seem to be with Mozilla Firefox @rahulporuri - link to highlight doesn't seem to work there. 

Btw @harshtandiya - there seem to some other browser specific issues too, like new tabs opening with every link click in Firefox. 

@wisharya had reported it around 2 weeks ago, but i am unable to reproduce it too. Maybe @Mangeshrex can look into it later - low priority now.

@wisharya can you please share an issue with a small screen-recording of some links that open a new tab ?

**Comment by RiyaMathew-11** [comment]
I've fixed this up, by enabling navigating to the section by id - this is the standard practice it seems. 

The navigate by text works only on chromium browsers. 

The CTA works on all now. - https://fossunited.org/city-communities#communitylist

**Comment by RiyaMathew-11** [comment]
I've fixed this up, by enabling navigating to the section by id - this is the standard practice it seems.

The navigate by text works only on chromium browsers.

The CTA works on all now. - https://fossunited.org/city-communities#communitylist

PS: This was also handled from desk.
