### ISSUE TITLE
[BUG] New City meetup doesn't show up on Events timeline

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#323]
### Describe the bug

The Hyderabad city chapter just created a [new city meetup event in June](https://fossunited.org/hyderabad) but the event does not appear on the ["Events" timeline](https://fossunited.org/events/timeline) page

**Comment by ansharora28** [comment]
Shows now. Refer to https://github.com/fossunited/fossunited/discussions/324#discussioncomment-9440683

**Comment by harshtandiya** [comment]
#325

**Comment by harshtandiya** [comment]
Closed with #333
