### ISSUE TITLE
Publish Events on Creation

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#325]
### Issue description

"Is Published" should be checked by default.

**Comment by RiyaMathew-11** [comment]
If published is checked by default - then would there be the need for Approved/Rejected states ? 

An event that get's approved is supposed to be published by default ? Or we should remove the status ?

**Comment by harshtandiya** [comment]
I think changing the publish state based on status is better. Anything other than Approved and Concluded can have it as unpublished

**Comment by RiyaMathew-11** [comment]
Then we should also decide on who approves the events too - if the org, maybe need notifications to alert once an event is created. @rahulporuri @wisharya please share your thoughts on this.

But there is also the overhead then that we have to bear of Approving the events too. The logic for concluded i think could automated once after end-date passes.

**Comment by rahulporuri** [comment]
I'm not sure what "Approval" even means here. Who needs to "Approve" events and why? I mentioned this in https://github.com/fossunited/fossunited/discussions/324

The Event Status state transitions are

Being Reviewed -> Approved -> In Progress -> Concluded
Being Reviewed -> Approved -> Cancelled
Being Reviewed -> Cancelled

Are those the appropriate state transitions?

And again, what does "Being Reviewed" mean here? Does it mean that the Org is reviewing an application to host an event on the platform? Does "Being Reviewed" mean that a volunteer is creating the event for the Chapter and the Chapter lead "Approves" it, making it publicly visible on the platform?

**Comment by harshtandiya** [comment]
Perhaps I should change the labels to be more descriptive.

Being reviewed is same as "Draft". I will change it to that.

No, we should not involve anyone from our side to Approve or Reject Events. This status is for organizers to keep track of events from their side. They can create draft events that they can make live, hence "Accepted", and at the end of the event, the status is supposed to go to "Concluded". 

There is the "Cancelled" status for organizers, as they cannot directly delete the event. They can mark it as cancelled, and we can run a schedule job for deleting these kind of events from our side.

Again, no involvement from our side. 

Being Reviewed will be changed to Draft. 
Draft and Cancelled Status == Event not published and not visible to public.
Approved == Event published and visible to public
Concluded == Visible to users as past events.

**Comment by RiyaMathew-11** [comment]
Instead of Approved - let's make the status log to `Live` then, IMO it's more understandable and relatable than Approved. 

I think Completed might sound better than Concluded too, from a naming perspective. 

- Draft
- Live
- Completed
- Cancelled

How does these sound @harshtandiya @rahulporuri ?

**Comment by rahulporuri** [comment]
Draft, Live, Completed/Concluded and Cancalled sounds good to me. And the state transitions are

```mermaid
stateDiagram-v2
  Draft --> Live
  Live --> Cancelled
  Live --> Concluded/Completed
```

Sidenote - if you didn't know, you can create [mermaid diagrams](https://mermaid.js.org/syntax/stateDiagram.html) and embed them into GitHub comments and/or markdown documents (that get rendered when viewed on GitHub)
