### ISSUE TITLE
[FEATURE] Add external events to the FOSS Events Timeline

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/fossunited#329]
### Feature description

Currently all FOSS events in our platform are bound to a FOSS Community or Club. 
The events in our [`timeline`](https://fossunited.org/events/timeline) are also confined to our communities and clubs. 

- Our old site had the provision for adding external events, and this feat could be implemented  in the new site. 

- The event cards in timeline, when clicked navigates to the corresponding event page, while in case of external events, it could navigate to the event website.  

### Use case

- Helps to add the FOSS events we partner with in our timeline. 
- The events timeline can slowly evolve to be a calendar for FOSS events.
- IndiaFOSS and FOSSHack too have different website pages.

**Comment by rahulporuri** [comment]
> Helps to add the FOSS events we partner with in our timeline.

We already have a usecase for this - React India is close to becoming a Community Partner and we would need to showcase their event in our events timeline.
