### ISSUE TITLE
[BUG] Exported RSVP list does includes email with * chars

### ISSUE THREAD

**Issue by mngshm** [fossunited/fossunited#342]
### Describe the bug

After exporting the list of RSVP's from an event/meetup. The emails are as shown in the below screenshot. I am guessing it shouldn't be like this for the download file as most meetup managers have to submit this list with the venue folks. 

### To Reproduce

navigate to fossunited.org/dashboard/<event>/insights and download the CSV file. 

### Screenshots

![ss](https://github.com/fossunited/fossunited/assets/82205152/1a79fc14-643d-41f3-be2b-bb42015e7243)

### Environment

```markdown
- Device:
- OS:
- Browser:
```

**Comment by harshtandiya** [comment]
They are supposed to be like that. We do not want the transfer of sensitive data such as emails, that was the whole point for masked emails anyway.

**Comment by harshtandiya** [comment]
See #255

**Comment by ansharora28** [comment]
If the security wants the emails just for identification purposes, the unmasked format should suffice for that. I kind of want to force this as a policy to the venues and say we can't share the complete email and see what they say :smile: 

If it's absolutely required, it can be still shared through the desk?

**Comment by mngshm** [comment]
>hat was the whole point for masked emails anyway.

The security or venue managers always ask for email and names of the potential attendees for the meetup. I don't know what their reaction would be when they see masked emails in the list provided to them. 

>If the security wants the emails just for identification purposes

Identification? I don't think they need emails just for identification 😁 and I don't understand how would they identify someone from email. Usuallly, its the cross-checking from the attendees side right ?

**Comment by harshtandiya** [comment]
Let's not handle data to these venues on a platter. Masked emails will continue, changes will be made according to #255
