### ISSUE TITLE
Event name and address on the payment invoice 

### ISSUE THREAD

**Issue by fossdot** [fossunited/fossunited#343]
### Issue description

Please mention the `event name` `date` and `address` on the payment invoice to avoid the confusion.

**Comment by harshtandiya** [comment]
Event name, event date and event address?

**Comment by rahulporuri** [comment]
@harshtandiya please confirm that this issue has been closed. @wisharya believes that this has been addressed.

**Comment by harshtandiya** [comment]
this was done through the desk.
