### ISSUE TITLE
[FEATURE] Including a "See on website" link on the dashboard page

### ISSUE THREAD

**Issue by mngshm** [fossunited/fossunited#345]
### Feature description

This is a feature request for having a "see on website link" on the Event Dashboard for viewing the web page of the chapter as soon as any change is made.

**Comment by mngshm** [comment]
Taking this up, will work on this. And hopefully push a pr in the upcoming 2-3 days.

**Comment by rahulporuri** [comment]
unassigning @Mangeshrex from this issue. i've also added it to the project and moved it to the Done column
