### ISSUE TITLE
[BUG] Limit of 3 events per month in All Events page

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#359]
### Describe the bug

There is a limit of 3 events per month to be shown in all events page. This is probably due to the default page_length of 3 set by frappe.

![image](https://github.com/fossunited/fossunited/assets/73123690/78a06509-5d44-46d1-85b3-8761e38eb407)

## Proposed solution
Increate the limit to `999` for a good measure.

**Comment by RiyaMathew-11** [comment]
@harshtandiya I am unable to reprrduce this issue - the timeline seems to render more than 3 events ? 

<img width="1191" alt="Screenshot 2024-06-03 at 3 25 13 PM" src="https://github.com/fossunited/fossunited/assets/60656677/d0e06aff-3a51-4cf6-a03e-bca6a1a53fff">

https://fossunited.org/events/timeline

**Comment by harshtandiya** [comment]
@RiyaMathew-11 could be a cache issue then.

**Comment by RiyaMathew-11** [comment]
Okay, closing the issue.
