### ISSUE TITLE
[FEATURE] Suggestion to change the update profile

### ISSUE THREAD

**Issue by Glitchyi** [fossunited/fossunited#366]
### Feature description

Wanted to suggest a simple change where the button for updating the profile info could be changed to the bottom of the profile from, currently it looks like this:
![image](https://github.com/fossunited/fossunited/assets/55801439/3968b89d-9edd-4132-915f-fd7929dd2379)

I feel the text could be changed to save changes and the button be shifted to the bottom, where after they users have finished updating their profiles they can save changes and head on back to the main page.

### Alternatives considered

Suggested change look
![image](https://github.com/fossunited/fossunited/assets/55801439/3a910266-4da2-46c5-97a9-cdb2fcefc8ec)

**Comment by rahulporuri** [comment]
Thanks for opening the issue @Glitchyi . We will discuss this and get back to you.

**Comment by captn3m0** [comment]
+1 to this. It is unintuitive to click the "Update Profile" button, to save my changes.

**Comment by harshtandiya** [comment]
I think I will move the profile settings stuff under dashboard. Would be neater that way too

**Comment by harshtandiya** [comment]
Closed with #410
