### ISSUE TITLE
IndiaFOSS 2024 page doesn't highlight CFP deadline

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#372]
### Issue description

The CFP deadline is drawing near but the deadline itself isn't publicized on the IndiaFOSS page - https://fossunited.org/events/indiafoss24.

See general issue for all events - #371

**Comment by harshtandiya** [comment]
![image](https://github.com/fossunited/fossunited/assets/73123690/571f32e8-0faf-47d1-bac4-b6906875c411)

![image](https://github.com/fossunited/fossunited/assets/73123690/ecfee42d-d576-47e1-8353-55be8a441679)
