### ISSUE TITLE
dashboard/event is blank

### ISSUE THREAD

**Issue by Delta456** [fossunited/fossunited#383]
### Issue description

When I go to https://fossunited.org/dashboard/event 

I see a blank page

### Steps to reproduce (if applicable)

Given above

### Expected behavior

I expected Forbidden or some error related to that.

### Additional context

The link works when `/event_hash_name` is appended to the link.

**Comment by mngshm** [comment]
Hi @Delta456, there isn't certainly any page on fossunited.org/dashboard/event, please checkout the [Dashboard Manager](https://fossunited.org/manual/)

**Comment by harshtandiya** [comment]
@Mangeshrex Yes, but we need to handle this case, where people may stumble upon this particular route, which will happen often imo

**Comment by Delta456** [comment]
Maybe redirect `dashboard/event` route to `dashboard`?
