### ISSUE TITLE
[BUG] Join Team Button not working for hackathons

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#387]
### Describe the bug

- A person should be able to join team through code, currently it doesn't seem to work

**Comment by rahulporuri** [comment]
@harshtandiya i thought this bug was addressed. I remember seeing a couple of discussions internally regarding this earlier, maybe last week. Are we able to reproduce this ourselves?

**Comment by harshtandiya** [comment]
@rahulporuri yes, turns out i did not write the logic for that button in the first place. my bad

**Comment by rahulporuri** [comment]
i've added this issue to the project and set status to Done
