### ISSUE TITLE
[DOCS] Instructions for running on Windows

### ISSUE THREAD

**Issue by iaayushmaan** [fossunited/fossunited#391]
### Documentation request

Currently, the documentation does not include methods for running on Windows.

**Comment by mngshm** [comment]
Hey, what do you mean by running on Windows ? Is it the FOSS United Frappe App or Frappe Framework ? 

FYI, Frappe Framework officially does not support running on Windows, it can only be installed and run on MacOS or any other distro from the Linux family. 

check: https://frappeframework.com/docs/user/en/installation

**Comment by harshtandiya** [comment]
Hey @iaayushmaan , for running on windows, I will suggest using [WSL](https://learn.microsoft.com/en-us/windows/wsl/). You can use any linux distro on WSL and follow the procedure to install Frappe Framework from [here](https://frappeframework.com/docs/user/en/installation). After that, I think the steps in our ReadMe would suffice

**Comment by iaayushmaan** [comment]
You're correct, @Mangeshrex! I'm familiar with it and have thoroughly reviewed the documentation. Specifically, I am referring to documenting alternative methods to run it on Windows as one mentioned by @harshtandiya.

**Comment by harshtandiya** [comment]
Closing this issue, seems like it's solved.
