### ISSUE TITLE
[FEATURE] Automate Ticket Transfers

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#400]
### Feature description

We need to automate ticket transfer process. Right now we need a dedicated person who looks into transfer queries and caters to them individually, it is very _inefficient_

Proposed solution: 

I am going with the assumption that we let the people do the monetary transactions with each other without FOSS United having any part in it. The organization's role will only be to change the ticket details

- Let's have a portal where people can transfer tickets
- People can enter their ticket ID and email + email of the person they want the ticket to be transferred
- Validation of Ticket ID + email. Once validated, email will be sent to the original ticket holder who will approve the request from email.
- Upon approval, the ticket details will be updated and a new email will be sent to the person receiving the ticket.

**Comment by RiyaMathew-11** [comment]
LGTM!

We could also add the provision of multiple tickets being exchanged in a single shot, so that people having 3 or 4 tickets to transfer can do it in one process.

**Comment by rahulporuri** [comment]
> We could also add the provision of multiple tickets being exchanged in a single shot, so that people having 3 or 4 tickets to transfer can do it in one process.

Just to confirm, if i were to buy multiple tickets, does each ticket have a unique ticket ID, hence each ticket ID can be transferred separately or all of the tickets bought using an email address can be transferred together? Is that how it works?

**Comment by harshtandiya** [comment]
@rahulporuri yes, each ticket has a unique ticket ID and is linked to a particular email address. So the idea is that a particular ticket owner can transfer their own ticket

**Comment by rahulporuri** [comment]
added to the GitHub project and set to Done
