### ISSUE TITLE
bug: team ID being shown in all projects page

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#404]
Bug Details:
Team IDs are being shown in project cards in all projects page. It would be ideal to show team name instead.

![image](https://github.com/fossunited/fossunited/assets/73123690/ed43d69d-3b0f-4f79-a182-90aa27203083)

Suggested Fix:
https://github.com/fossunited/fossunited/blob/70b0e362661d7169c6d544c3e7e72b61520b3bb4/fossunited/www/hackathon/projects.html#L37C60-L37C64

This piece of code needs to replace the `project.team` with `project.team_name`

**Comment by mngshm** [comment]
Understood, I'll take this up @harshtandiya. Will push the fix in some time

**Comment by rahulporuri** [comment]
added issue to the board and moved to done
