### ISSUE TITLE
[BUG] Unable to enlist a partner project contribution in hackathon dashboard

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/fossunited#407]
### Describe the bug

In the hackathon dashboard, when one selects `Contributing to Partner Projects` - the `Repository Link` field gets disabled. 

But without a repository link, it is not possible to complete the project creation process too. 

### To Reproduce

1. Go to hackathon dashboard for [FOSS Hack](https://fossunited.org/dashboard/hack/fosshack24)
2. Create a project and choose `Contribute`
3. Select `Contributing to Partner Projects` and go on with rest of the workflow. 

### Screenshots

<img width="1201" alt="Screenshot 2024-06-23 at 12 06 03 AM" src="https://github.com/fossunited/fossunited/assets/60656677/31b5c1f6-1242-4d35-9694-05ed1caa6d40">

### Additional context

As part of the process - it was suggested to the participants, to add in the project repo link/link to the fork first while creating projects, and replace it with a link to PR/draft PR later on when they start working. 

Refer [guidelines](https://fossunited.org/fh24/partner-projects)

**Comment by harshtandiya** [comment]
Select a partner project from the list above the form. The repo link should autofill, given that the repo link is provided in the Partner Project doctype

Also, I don't see a repo link for **Keyshade, Phase, Vibenx, Raven and Hoppscotch**. Please update
![image](https://github.com/fossunited/fossunited/assets/73123690/60ab8d1c-8f67-4e19-8608-01034baca9c3)
![image](https://github.com/fossunited/fossunited/assets/73123690/ae7b450f-79b1-4823-8bb0-8bc31feafa40)
![image](https://github.com/fossunited/fossunited/assets/73123690/eff634e2-861d-4c64-bb35-9e8e9fc8d776)
![image](https://github.com/fossunited/fossunited/assets/73123690/91861faa-d40d-48fb-9640-a8f5b4e5a8f8)
![image](https://github.com/fossunited/fossunited/assets/73123690/4514b68f-fad4-4049-b9b7-daaf540bce18)

**Comment by RiyaMathew-11** [comment]
Ohh - this case of autofilling was quite an unawared case - I had filled up the other links just for reference, and was hoping to fill the rest later on. 

If the case with this process had been documented/mentioned somewhere - I think it would have been helpful. 

One add-on query - if the repo link field is non-editable - where can folks add links to their PRs ? - based on this, I will edit the [guidelines](https://fossunited.org/fh24/partner-projects)

The demo link field would also be needed to add video demos if they wish to add.

**Comment by RiyaMathew-11** [comment]
Update: have opened an issue relevant to adding PR links, based on the discussion we had - #408

Closing this issue.
