### ISSUE TITLE
[FEATURE] "/non-profit" page (placeholder name)

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#409]
### Feature description

Tinkerhub has a page where all of the information pertaining to their not-for-profit status is mentioned (https://www.tinkerhub.org/non-profit) e.g. PAN, 12AA, 80G, CSR1 and other registrations, their registered address, etc.

Internet Freedom Foundation has a ["Transparency"](https://internetfreedom.in/transparency-and-finances/) page where they provide easy access to ITR filings, registration documents (not just registration numbers), etc.

**Comment by mngshm** [comment]
What all things do we need to mention on this web page of ours ? 

Things I have in my mind are: 
2. 80G
3. Registered Address 
4. Our Annual Reports
5. And ?

**Comment by rahulporuri** [comment]
> Our ISO Certification

I didn't even know that we had an ISO certification. But yes, everything that we listed. We also have a 12A certificate that we should link. And I think we also have a CSR1 registration.

We should also mention our PAN number. I don't think the PAN number should be kept private - and if we're showing the other certificates, i'm sure the PAN number will be shown.

Please do take a look at the IFF and Tinkerhub pages @mangeshrex if you have not already done so

**Comment by mngshm** [comment]
Hey, ok understood. I'll take the above documents from Vishal and get this issue done. 

Yes, I went through both the IFF and Tinkerhub transparency pages.

**Comment by rahulporuri** [comment]
> Hey, ok understood. I'll take the above documents from Vishal and get this issue done.

Thank you. Let's move these documents to NextCloud and link to them from our website. I dont know if PDF assets can be stored directly on our website.

**Comment by mngshm** [comment]
Yes, PDF assets can be stored on the Frappe App (fossunited). But, I think add them to nextcloud as it'll be better to store them on our instance as well. So, both the requirements will be satisfied.

**Comment by mngshm** [comment]
https://fossunited.org/non-profit this is done. closing the issue.
