### ISSUE TITLE
Centralizing Dashboard

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#410]
### Issue description

- Move Profile setting under dashboard. linked to #366 
- My hackathons page in dashboard for all the users.
- Make the dashboard available to everyone, and render the sections as per the roles
- Right now, there's no easy way to access the dashboard. Hence, I propose a direct way to access a dashboard by adding a "Go To Dashboard" button in this section: 
![image](https://github.com/fossunited/fossunited/assets/73123690/49d9ddb3-ca78-4810-8717-ac917e1ce1e2)

**Comment by RiyaMathew-11** [comment]
So it's going to be My Dashboard CTA, which navigates to a portal dashboard page, having views/sections about: 

- My Profile
- Events (potentially add CFPs submitted data for now?)
- Chapters (if a chapter volunteer/lead)
- Hackathons

etc., ?
