### ISSUE TITLE
[BUG] Too many search indexes

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#412]
### Describe the bug

A lot of doctypes have the `index_web_pages_for_search` enabled, which i think is unnecessary. It it resulting in slow cloud updates. 

![image](https://github.com/fossunited/fossunited/assets/73123690/4d24a1a1-7160-474b-8dc2-ed27ff7b9a36)

Proposed solution: let's disable `index_web_pages_for_search` for majority of doctypes such as Tickets, Participants etc

**Comment by rahulporuri** [comment]
added the issue to the project and moved to June
