### ISSUE TITLE
[DOCS] need of SECURITY.md 

### ISSUE THREAD

**Issue by mngshm** [fossunited/fossunited#421]
### Documentation request

The project needs a security.md document to outline all the guidelines for folks to submit security related reports and bugs. 

Examples: 
https://frappe.io/security
https://github.com/hoppscotch/hoppscotch/blob/2917d50c6afe5f52fdcbb284514099d8423eca79/SECURITY.md#L4

**Comment by rahulporuri** [comment]
I've added this to the GitHub Project and put it into the Todo column.
