### ISSUE TITLE
[FEATURE] Implementing proper routes for user and chapters on the platform

### ISSUE THREAD

**Issue by mngshm** [fossunited/fossunited#424]
### Feature description

There is a lot of confusion between the routes of a user profile and a chapter profile.

**Comment by harshtandiya** [comment]
Let's have users under `/u/`, ex: `fossunited.org/u/harsh` ?

For cities, we can either have them as they are currently, i.e, `fossunited.org/<city_name>` or we can move them under `/c/`. Thoughts on this?

**Comment by rahulporuri** [comment]
- `/u/` or `/user/` for individual users
- `/c/` or `/community/` for communities, city chapters & student clubs e.g. `/community/hyderabad` and `/community/iiit-kalyani`. i don't think the URLs need to differentiate between them

**Comment by harshtandiya** [comment]
I think having the cities at the top level without `/c/` would work too. Cities are limited anyway. For student clubs, we should indeed move them under `/c/` imo.

After the refactor of chapter routes, the event routes for City Chapters can be made to be like this:
`fossunited.org/bengaluru/2024/june`

or if we go with `/c/` for city communities too:
`fossunited.org/c/bengaluru/2024/june`


For clubs it can be under `/events/` or we can change it to be under the chapter's path:
`fossunited.org/c/iiit-kalyani/linux-installation-2024/`
`fossunited.org/c/iiit-kalyani/2024/catch-the-flag`

I need help to have more clarity on this.


Pros for having cities on top level:
- Easier to access chapter pages
- Shorter routes for events

Cons:
- More code to handle different cases but manageable

**Comment by rahulporuri** [comment]
> I think having the cities at the top level without /c/ would work too. Cities are limited anyway. For student clubs, we should indeed move them under /c/ IMO.

I would prefer strictly namespacing the cities now, while we're making the changes. Cities are limited but we could have 100s of city chapter a decade from now, in different stages of activity

> After the refactor of chapter routes, the event routes for City Chapters can be made to be like this:

for the events, I would recommend the format `/c/<chapter-identifier>/year/<event-identifier>` - the chapter identifiers have to be unique i.e. a city chapter will use the city name and clubs in the city will use the college name. the event identifiers have to also be unique e.g. month name if only one event happens per month or unique identifiers like mini hackathon, cityfoss, x workshop, etc.

@captn3m0 thoughts?

**Comment by captn3m0** [comment]
Enforcing /c/ and /u/ sounds good. Having a consistent URL scheme for the events that included the date is always good as well - it makes it obvious that the event is in the past or the future.

The month could be left to convention (event identifier), but would be nice to have it included in the URL (/c/City/YYYY-MM/event-identifier).

**Comment by harshtandiya** [comment]
This change was deployed, and around ~8.5k accounts were updated with the new route rules.

Some ~400 accounts had some errors in updating to new route. The reasons were one of the following:
- For usernames > 30 chars long, it resulted in a username too long error & route too long error.
- `Current City` field is a `Link` field which is linked to a `City` doctype. Ideally, this field should be a `Data` type field, which only stores text. We were using [Frappe's Database APIs](https://frappeframework.com/docs/user/en/api/database) in the dashboard until recently, which bypass all [document controllers](https://frappeframework.com/docs/user/en/basics/doctypes/controllers) of a doctype. Because of this, the framework was not able to Validate the link fields. For the fix, I decided to remove the current cities value from the required documents since we can consider this field to be of low importance.
- Invalid URL type in some of the fields which required a URL type data (starts with `https://`)


Most of it was solved via system console in the desk.

#### Reference code for fix:
```py
profiles = frappe.get_all("FOSS User Profile", {"route": ["not like", "u/%"]}, ["*"])

errors = int(0)

for p in profiles:
    doc = frappe.get_doc("FOSS User Profile", p.name)
    try:
        doc.save()
    except Exception as e:
        if "Could not find Current City" in str(e):
            frappe.db.set_value("FOSS User Profile", p.name, "current_city", "")
            continue
        if "Username can only contain lowercase letters, numbers, underscores and dots" in str(e) or "Username must be between 3 and 30 characters" in str(e):
            old_username = doc.username
            
            # List of allowed characters
            allowed_chars = "abcdefghijklmnopqrstuvwxyz0123456789_."
        
            # Convert username to lowercase
            username = doc.username.lower()
        
            # Build sanitized username by including only allowed characters
            sanitized_username = ''.join([char for char in username if char in allowed_chars])
            sanitized_username = sanitized_username + 'xyz'
            
            # Ensure the username is between 3 and 30 characters
            if len(sanitized_username) < 3:
                sanitized_username = sanitized_username.ljust(3, 'a')  # Pad with 'a' if too short
            elif len(sanitized_username) > 30:
                sanitized_username = sanitized_username[:26]  # Truncate if too long
            
            
            frappe.db.set_value("FOSS User Profile", p.name, "username", sanitized_username)
            
            content = f'''
                Hello {doc.full_name},

                We’ve been working on improving the architecture and security of the FOSS United website to make it more robust. As part of these updates, we needed to change the usernames of several users, including yours. While we understand that this change might be inconvenient, we hope you can appreciate that it was necessary for the overall improvement of the platform.
                
                Your username was updated for the following reason(s): {str(e)}.
                
                The change from your previous username, {old_username}, to the new one, {sanitized_username}, has been made.
                
                If you’d like to modify your username, please log in to https://fossunited.org/dashboard and update it as needed.
                
                Thank you for your understanding!
                
                Best regards,
                Team FOSS United
                
            '''
            frappe.sendmail(recipients = [doc.email], subject="Changes to your account at FOSS United" ,content=content, as_markdown=True, reference_doctype="FOSS User Profile", reference_name=p.name)
            
            print(f'Updated username for {p.name} from {old_username} to {sanitized_username}')
            print('----------------')
            continue
        errors = errors + 1
        print(f'{p.name} - {str(e)}')
        print("-----------")
            
```
