### ISSUE TITLE
Mention of privacy policy in the RSVP form

### ISSUE THREAD

**Issue by nk521** [fossunited/fossunited#428]
If the user is not logged in then at the time of RSVP there should be a text mentioning `By clicking on the submit button, you agree to our [privacy policy](link it) ...` under the submit button. This is because fossunited stores RSVP data but lacks to let the guest users know about it. 

![image](https://github.com/fossunited/fossunited/assets/30789322/957a34e6-01a6-47a5-b844-d227496b4927)

**Comment by mngshm** [comment]
Should there be a detailed document on the Privacy Policy of the platform, which the user will agree to ?

**Comment by nk521** [comment]
The privacy policy that is linked in footer has sufficient text. You can link the same here.

**Comment by rahulporuri** [comment]
I've added the issue to the GitHub project and set status to "In Progress"
