### ISSUE TITLE
[BUG] GST Numbers aren't adding up

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/fossunited#444]
### Describe the bug

![image](https://github.com/fossunited/fossunited/assets/60656677/f7a2de09-b987-441c-a915-0a0a05b9d18e)

This is from a revised invoice sent on 19th June. 

[Reported on Telegram Public Group](https://t.me/fossunited/54660/74732) - the numbers don't seem to add up. 

- Need to verify first if this is an outdated issue.

**Comment by harshtandiya** [comment]
This was fixed on desk.
