### ISSUE TITLE
Need of a CONSTANTS file

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#446]
### Issue description

Need to create a top level module/file to define all the doctype names as constants, which can be imported and used in tests.
This will improve maintainability of code

**Comment by rahulporuri** [comment]
additional context - at the moment, the doctype string identifiers are duplicated across the code base e.g. "FOSS Event" which leads to potential trivial bugs e.g. spelling mistakes that could be prevented if we define string constants e.g. `EVENT_DOCTYPE = "FOSS Event"` and import it where necessary e.g. `from fossunited.doctype_constants import EVENT_DOCTYPE`.

**Comment by RiyaMathew-11** [comment]
Closing this issue, as it's same as #485 has been created and is being worked upon. 

Both issues are duplicates.
