### ISSUE TITLE
[BUG] Payment invoice pdf is blank

### ISSUE THREAD

**Issue by maheshrijal** [fossunited/fossunited#449]
### Describe the bug

Payment invoice pdf sent over mail is blank. 

### Screenshots

![image](https://github.com/fossunited/fossunited/assets/62394512/e3d443b3-41f9-4354-a08f-ebe71521ae3d)

### Environment

```markdown
- Device:
- OS:
- Browser:
```

**Comment by harshtandiya** [comment]
This is fixed. Please email at indiafoss@fossunited.org if you did not receive the new invoice. You can also CC developers@fossunited.org
