### ISSUE TITLE
[BUG] Unable to "Edit" Proposal Review

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#468]
### Describe the bug

I was reviewing Proposals for the Chennai July meetup and I wanted to go back to Edit one of my reviews, which I was unable to.

### To Reproduce

* As a reviewer, visit one of the proposals at https://fossunited.org/events/chennai-july-24/cfp/all
* Add a review to a proposal
* Attempt to edit the proposal

### Screenshots

![edit-review-broken](https://github.com/user-attachments/assets/88cf7c71-5368-4189-ab74-9ccaaa1eadb6)

**Comment by harshtandiya** [comment]
This is resolved with the reviewer dashboard
