### ISSUE TITLE
BUG: Review Status field is necessary but it isn't marked as such on Review form 

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#469]
### Issue description

When submitting a proposal review, it isn't obvious at the moment that the "Review Status" field is required i.e. one of the options "Accepted"/"Rejected"/"Not Sure" needs to be selected. When I tried to click "Post your review" without selecting the option, nothing happened. When I selected the "Review Status", I was able to click "Post your review" successfully.

It will be useful to mark the "Review Status" field as required.

![image](https://github.com/user-attachments/assets/7e4d6dce-6324-4cc4-9bde-d8e3a30ed217)

**Comment by harshtandiya** [comment]
Resolved with reviewer dashboard #510
