### ISSUE TITLE
[BUG] Attempting to access the "All proposals" page leads to a 404

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#471]
### Describe the bug

Attempting to access the "All Proposals" page at https://fossunited.org/events/2024/july leads to a 404

### To Reproduce

- open fossunited.org
- access the /events page
- open the Bengaluru meetup page for July
- open the "Talk Proposal" tab
- Click on "View all Proposals"

**Comment by harshtandiya** [comment]
Not fixing this as the talks already have been finalized by the Bangalore Chapter & RSVPs are ongoing. 
This issue is due to the permalink format. Same issue happened with Chennai which was fixed earlier this week.

Perhaps a more rigid permalink format rules need to be created

**Comment by rahulporuri** [comment]
> Perhaps a more rigid permalink format rules need to be created

Yes. `/` in permalink should not be allowed in my personal opinion/understanding

**Comment by mngshm** [comment]
Closed in favor of #509
