### ISSUE TITLE
[BUG] Hackathons - Filters for requests aren't working in localhost dashboard

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/fossunited#475]
### Describe the bug

While changing status for requests in the filters of localhost dashbaord, the view isn't updated. 

On a refresh, it goes back to all requests. 
![Screenshot 2024-07-17 at 12 40 36 PM](https://github.com/user-attachments/assets/2dc9875f-c631-47e2-b492-d2116ce252d0)

Add-on: The numbers of pending requests aren't updated too. 

Browser: Chrome, Arc

**Comment by harshtandiya** [comment]
#478

**Comment by RiyaMathew-11** [comment]
Reopening this issue @rahulporuri @harshtandiya, as this bug came back after the recent PR, as fix got reverted.
