### ISSUE TITLE
[FEATURE] New "doctype_ids" module

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#485]
### Feature description

The identifiers of the various doctypes in the codebase are distributed and there is no central place where they are documented. Because of this, we have a case where the doctype id strings are being duplicated in a number of different locations, causing potential issues e.g. trivial spelling mistakes. It will be useful to have a `doctype_ids` (naming things is hard) module where we document this information. The rest of the `fossunited` codebase can then import from this module.

**Comment by RiyaMathew-11** [comment]
I think the issue is same as #446?

**Comment by rahulporuri** [comment]
sigh. yes. they're duplicates. i forgot about the previous issue :/

**Comment by mngshm** [comment]
The older PR was pretty messed up and it became even more complicated because of the merge conflicts. I am reopening a fresh PR today.

**Comment by rahulporuri** [comment]
> The older PR was pretty messed up and it became even more complicated because of the merge conflicts. I am reopening a fresh PR today.

Thanks for the headsup @Mangeshrex .

**Comment by mngshm** [comment]
Format: <constant_variable = <doctype_name> 

#### Chapters Module 

- [x] `CHAPTER` = "FOSS Chapter"
- [x] `CHAPTER_EVENT` = "FOSS Chapter Event"
- [ ] `CHAPTER_EVENT_MEMBER` = "FOSS Chapter Event Member" 
- [ ] `EVENT_PARTICIPANT` = "FOSS Chapter Event Participant" 
- [ ] `CHAPTER_LEAD` = "FOSS Chapter Lead Team Member" 
- [ ] `EVENT_COMMUNITY_PARTNER` = "FOSS Event Community Partner"
- [x] `EVENT_RSVP` = "FOSS Event RSVP" 
- [x] `RSVP_SUBMISSIONS` = "FOSS Event RSVP Submissions"
- [ ] `EVENT_TYPE` = "FOSS Event Type"
- [ ] `TICKET` = "Conference Ticket" 

### FOSS Profiles Module

- [x] `USER_PROFILE` = "FOSS User Profile"
- [ ] `USER_EDUCATION` = "FOSS User Profile Education" 
- [ ] `USER_WORK_EXPERIENCE` = "FOSS User Profile Work Experience" 
- [ ] `USER_SKILL` = "FOSS User Skill" 
- [ ] `USER_SKILL_MULTISELECT` = "FOSS User Skill Multiselect" 
- [ ] `USER_PROJECTS` = "FOSS User Projects" 

### FOSS Hackathon Module

- [x] `HACKATHON` = "FOSS Hackathon" 
- [x] `JOIN_TEAM_REQUEST` = "FOSS Hackathon Join Team Request" 
- [x] `HACKATHON_LOCALHOST` = "FOSS Hackathon Localhost" 
- [x] `LOCALHOST_ORGANIZER` = "FOSS Hackathon Localhost Organizer"
- [ ] `HACKATHON_MENTOR` = "FOSS Hackathon Mentor" 
- [x] `HACKATHON_PARTICIPANT` = "FOSS Hackathon Participant" 
- [x] `HACKATHON_PARTNER_PROJECT` = "FOSS Hackathon Partner Project" 
- [x] `HACKATHON_PROJECT` = "FOSS Hackathon Project" 
- [x] `HACKATHON_TEAM` = "FOSS Hackathon Team" 
- [x] `HACKATHON_TEAM_MEMBER` = "FOSS Hackathon Team Member" 

### Ticketing Module

- [x] `EVENT_TICKET` = "FOSS Event Ticket" 
- [x] `TICKET_TRANSFER` = "FOSS Event Ticket Transfer" 
- [ ] `TICKET_CUSTOM_FIELD` = "FOSS Event Ticket Field" 
- [ ] `TICKET_TIER` = "FOSS Ticket Tier" 
- [ ] `TICKET_TRANSFER_SETTINGS` = "Ticket Transfer Settings" 

### Payments Module 

- [ ] `RAZORPAY_PAYMENT` = "Razorpay Payment" 
- [ ] `RAZORPAY_SETTINGS` = "Razorpay Settings" 
- [ ] `RAZORPAY_WEBHOOK_LOGS` = "Razorpay Webhook Log"

### FOSSUnited Module

- [ ] `REVIEW_TEMPLATE` = "CFP Review Template" 
- [ ] `REVIEW_TEMPLATE_REASON` = "CFP Review Template Reason" 
- [ ] `CUSTOM_ANSWER` = "FOSS Custom Answer" 
- [ ] `CUSTOM_QUESTION` = "FOSS Custom Question` 
- [x] `EVENT_CFP` = "FOSS Event CFP" 
- [x] `CFP_REVIEW` = "FOSS Event CFP Review" 
- [ ] `CFP_REVIEWER` = "FOSS Event CFP Reviewer" 
- [ ] `EVENT_FIELD` = "FOSS Event Field" 
- [ ] `EVENT_GRANT` = "FOSS Event Grant" 
- [ ] `EVENT_SCHEDULE` = "FOSS Event Schedule" 
- [ ] `EVENT_SPONSOR` = "FOSS Event Sponsor" 
- [ ] `GLOBAL_CFP_REVIEWER` = "FOSS Global CFP Review Member" 
- [ ] `GLOBAL_REVIEW_SETTINGS` = "FOSS Global CFP Review Settings" 
- [ ] `PROJECT_GRANT` = "FOSS Project Grant" 
- [ ] `TEAM` = "FOSS United Team" 
- [ ] `FOSSUNITED_SETTINGS` = "FOSSU Settings"
- [ ] `INDUSTRY_PARTNERS` = "Industry Partners" 
- [ ] `ORGANIZATION` = "Organization"
- [ ] `STATE` = "State"  

### Volunteering Module 

- [ ] `EVENT_VOLUNTEER` = "Event Volunteer" 
- [ ] `NGO_NPO_VOLUNTEER` = "NGO or NPO Volunteer" 
- [ ] `VOLUNTEERS` = "Volunteers" 


@harshtandiya @rahulporuri @RiyaMathew-11 Please check the list for any edits in the variable names and if I have missed any of the doctype. I've tried covering all the doctypes from all the modules.

**Comment by RiyaMathew-11** [comment]
```
- [ ] EVENT_VOLUNTEER = "Event Volunteer"
- [ ] MEETUP_VOLUNTEER = "Meetup Volunteer"
```

Would we need Event and Meetup Volunteer ? - as one is a child of another ? 

Off-context:
Check on the codebase, I see the meetup volunteer doctype isnt used anywhere, and can be avoided ?

---

> FOSSU_SETTINGS = "FOSSU Settings" 

To FOSSUNITED_SETTINGS ? if can be extended, the doctype could be renamed the same way too. (later on)

If we could use just `SETTINGS`, that would've been good, but I think there is another frappe doctype named `Settings`.

**Comment by rahulporuri** [comment]
>  Check on the codebase, I see the meetup volunteer doctype isnt used anywhere, and can be avoided ?

I'm having similar off-context but related questions when I go through the list of custom doctypes that we created.

**Comment by rahulporuri** [comment]
> To `FOSSUNITED_SETTINGS` ? if can be extended, the doctype could be renamed the same way too. (later on)

I agree here. In general, I recommend not using contractions e.g. `EVENT_COMMUNITY_PARTNER` instead of `EVENT_COMM_PARTNER`. The good thing with longer variable names is that auto-complete in most IDEs means that we don't actually have to type the whole variable ourselves. This isn't true with the strings (one more reason why the variables are better than duplicating strings)

**Comment by mngshm** [comment]
In consideration to both your comments, I've done the following changes

- Got rid of `MEETUP_VOLUNTEER`. 
- Replace `FOSSU_SETTINGS` with `FOSSUNITED_SETTINGS`

**Comment by rahulporuri** [comment]
@Mangeshrex i would recommend the following additional changes. After this, I would start adding the IDs grouped by the same context e.g. complete the FOSS Profiles module first, then move on to Chapters module, etc

- `USER_WORK_EXPERIENCE` instead of `USER_WORK_EXP`
- `USER_SKILL_MULTISELECT` instead of `USER_SKILL_MULTI`
- `RAZORPAY_PAYMENT` instead of `RZP_PAYMENT`
- `RAZORPAY_SETTINGS` instead of `RZP_SETTINGS`
- `RAZORPAY_WEBHOOK_LOG` instead of `RZP_WEBHOOK_LOGS`

a few tangential but relevant comments/questions @harshtandiya 

- what is the difference between a `FOSS Chapter Event Member` and an `FOSS Chapter Event Participant`
- why is `FOSS User Skill Multiselect` even a doctype?
- what are `CFP Review Template`, `CFP Review Template Reason`, `FOSS Custom Answer`, `FOSS Custom Question`
- shouldn't `FOSS Event CFP Reviewer` be a role assigned to an existing profile instead of a completely new doctype?
- what is an `FOSS Event Field`
- what are `FOSS Global CFP Review Member` and `FOSS Global CFP Review Settings`?
- what is `FOSS United Team`
- what is `STATE`
- is anything from the Volunteering module necessary? Are `Volunteers` and `NGO or NPO Volunteer` necessary or can we just remove them?

**Comment by mngshm** [comment]
@rahulporuri I've updated the constants like you mentioned. Also the PR for FOSS User Profile was merged yesterday. I am opening a new PR for swapping FOSS Hackathon Doctypes with the constants today one by one.

**Comment by harshtandiya** [comment]
@rahulporuri 

- I think `FOSS Chapter Event Participant` is deprecated. It has never been used, atleast not by me.
- This is again something that was planned but was not executed.
- `CFP Review Template` & `CFP Review Template Reason` were once created on this idea of showing certain pre made reasons to the reviewers at the time of their review. This is deprecated. I plan on removing these two doctypes and having only one. `FOSS Custom Answer` and `FOSS Custom Question` are used in RSVP and CFP form creation. `FOSS Custom Question` doctype is used to create custom questions on the form by the organizer. `FOSS Custom Answer` is a child table in each `FOSS <CFP/RSVP> Submission` which contains the answers of these custom questions.
- `FOSS Event CFP Reviewer` is a child table attached to every `CFP` form document created by the organizer. This has the list of reviewers for the particular event that is linked to this cfp form. This enables adding reviewers on event basis.
- `FOSS Event Field` was most probably created by Hussain while he was working on tickets. It is a child table doctype that has fields for custom questions that are rendered while buying tickets. The naming could be better tho
- `FOSS Global CFP Review Settings` is a Single doctype that has a child table of doctype `FOSS Global CFP Review Member`. This child table has details of a `Reviewer`. A person is set as a reviewer by adding them in this doctype.
- `FOSS United Team` was created by @RiyaMathew-11, so I think she can tell more about it.
- `State` has data of India's states and UTs. For some reason Frappe doesn't come with it out of box, so we had to create it from scratch.
- No, Volunteers is totally deprecated

**Comment by mngshm** [comment]
https://github.com/fossunited/fossunited/pull/516 PR covering all the Hackathon modules.

**Comment by RiyaMathew-11** [comment]
> FOSS United Team was created by @RiyaMathew-11, so I think she can tell more about it.

FOSS United Team holds needed data of the folks involved in FOSS United Org - Full Time/ Part Time staff, interns, Board, Org Level volunteers. 

This data is being pulled to fill in the Team section in the Home Page and Team Page of the platform. 

- Includes factors like - Is currently working, Designation etc. 

---

In case of a rename, this might be named as Org Team / Organisation Team - `ORGANISATION_TEAM` would be suited for variable name. 

Thoughts @rahulporuri ?

**Comment by Mangeshrex** [comment]
have added the needed constants for the doctype. Here's the list of doctypes which will/are be deprecating/deprecated:
- ~~[] `REVIEW_TEMPLATE` = "CFP Review Template" ~~
- ~~[] `REVIEW_TEMPLATE_REASON` = "CFP Review Template Reason"~~
- [x] `CUSTOM_ANSWER` = "FOSS Custom Answer" 
- [x] `CUSTOM_QUESTION` = "FOSS Custom Question` 
- [x] `EVENT_CFP` = "FOSS Event CFP" 
- [x] `CFP_REVIEW` = "FOSS Event CFP Review" 
- [x] `CFP_REVIEWER` = "FOSS Event CFP Reviewer" 
- [ ] `EVENT_FIELD` = "FOSS Event Field" 
- [ ] `EVENT_GRANT` = "FOSS Event Grant" 
- [ ] `EVENT_SCHEDULE` = "FOSS Event Schedule" 
- [ ] `EVENT_SPONSOR` = "FOSS Event Sponsor" 
- [ ] `GLOBAL_CFP_REVIEWER` = "FOSS Global CFP Review Member" 
- [ ] `GLOBAL_REVIEW_SETTINGS` = "FOSS Global CFP Review Settings" 
- [ ] `PROJECT_GRANT` = "FOSS Project Grant" 
- [ ] `TEAM` = "FOSS United Team" 
- [x] `FOSSUNITED_SETTINGS` = "FOSSU Settings"
- [ ] `INDUSTRY_PARTNERS` = "Industry Partners" 
- [ ] `ORGANIZATION` = "Organization"
- [x] `STATE` = "State"
