### ISSUE TITLE
[FEATURE-DOCS] Add docs to github repo

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/fossunited#490]
### Feature description

The current little docs structure is within wiki which is in this frappe desk. 
The context of how the manual for dashboard usage is written - https://fossunited.org/manual/getting-ready

It would be helpful if it's maintained within the Github repo of our platform within a `docs` directory.

For example - [Listmonk docs](https://listmonk.app/docs/)
Source: https://github.com/knadh/listmonk/tree/master/docs/docs

### Benefits

Makes it better maintainable and more open to contributions.

**Comment by sundaresan0502** [comment]
@RiyaMathew-11 currently are those docs hosted on some where ? or just written on the website ?

**Comment by RiyaMathew-11** [comment]
Apologies for the delayed reply @sundaresan0502 

These docs - https://fossunited.org/manual/getting-ready are actually made in frappe wiki, an instance in the frappe cloud. They can currently be updated from within the desk only.

Hence to make them open - we need this workflow
