### ISSUE TITLE
[BUG] New dashboard view is not rendering chapter tab

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/fossunited#491]
### Describe the bug

The new dashboard does not render the tabs relevant to chapter - that a user leads or is a volunteer of. 

![Screenshot 2024-07-20 at 8 09 23 PM](https://github.com/user-attachments/assets/fd9ec0a3-131f-40f6-9708-3eabc31a4e5d)

### Environment

```markdown
- Device: Macbook Pro
- OS: macOS Sonoma v14.2
- Browser: Chrome, Arc
```

**Comment by harshtandiya** [comment]
It seems like it loads sometimes, whereas it does not other times. I wonder if the api is slow?

**Comment by harshtandiya** [comment]
[Screencast from 2024-07-22 11-28-05.webm](https://github.com/user-attachments/assets/62b0af99-b746-43f1-b52d-7995adb19fab)

**Comment by rahulporuri** [comment]
This is consistently failing for me on Firefox and a priority.

**Comment by rahulporuri** [comment]
I've added the issue to the GitHub project and moved it to "ToDo"

**Comment by harshtandiya** [comment]
It seems like this issue is not occurring anymore.
Please check @rahulporuri @RiyaMathew-11 @Mangeshrex

**Comment by mngshm** [comment]
Agreed with @harshtandiya. We just tested it some time ago

**Comment by RiyaMathew-11** [comment]
I am still able to reproduce this: 

- Chapter tab isnt there in Chrome, macOS 14.2

<img width="1243" alt="Screenshot 2024-08-02 at 11 03 03 AM" src="https://github.com/user-attachments/assets/07ea48ea-6a07-4621-b21d-0eaf9f3984c2">

Plus did a test with Shahmil from Kochi, who reported the same for his iOS too. 

Would be good to get it tested with some Windows users and Android users and see if reproducible. And if this issue is confined to only iOS/macOS users.
