### ISSUE TITLE
[BUG] Event status in dashboard does not match with badge 

### ISSUE THREAD

**Issue by RiyaMathew-11** [fossunited/fossunited#492]
### Describe the bug

The event status shows concluded, yet the badge next to event title reflects the event being live. 

![Screenshot 2024-07-20 at 8 14 20 PM](https://github.com/user-attachments/assets/f59d132a-031d-4564-9180-90e2c4601fdd)
![Screenshot 2024-07-20 at 8 15 53 PM](https://github.com/user-attachments/assets/6c67065e-0fd9-4dbb-adb2-0ba9220b9223)

**Comment by RiyaMathew-11** [comment]
Have reproduced this again @Mangeshrex @rahulporuri @harshtandiya: 

![chapter-event](https://github.com/user-attachments/assets/f140f061-0fe3-472c-882b-e2d83126680a)

Device Specs: Chrome | macOS 14.2

**Comment by harshtandiya** [comment]
https://github.com/user-attachments/assets/22690a3a-dcaa-4384-b604-d0121fb37606

~I think this is no longer an issue? I am sure I fixed it sometime ago~

Update: nvm, it is broken. But for a different reason now. see #647

**Comment by RiyaMathew-11** [comment]
Re-opening this as there is still an edgecase to the status mismatch: The event status shows Live on Banner when actual status is concluded
