### ISSUE TITLE
[BUG] Email notification about job posting has broken link

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#496]
### Describe the bug

In the text "Find all the posted jobs [here](https://fossunited.org/app/job-post).", the following link is used https://fossunited.org/app/job-post - which goes to a 404.

**Comment by mngshm** [comment]
This is now fixed. 

The right url from now will be `https://fossunited.org/app/job-board`

**Comment by mngshm** [comment]
Closing this issue, since this is now fixed.
