### ISSUE TITLE
[BUG] Text formatting is broken in Job description

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#497]
### Describe the bug

Please see https://fossunited.org/jobs/um3i9g5fut for broken text formatting

**Comment by mngshm** [comment]
Hey, this is fixed. 

The applicant did not write the Job Description in markdown while filling the form.

**Comment by rahulporuri** [comment]
> The applicant did not add markdown guidelines while filling the form.

I'm not sure what markdown guidelines are. How do we prevent this from happening in the future?

**Comment by mngshm** [comment]
I'm don't have much idea about that. To make the job description section look precise, we use markdown which is then converted to html with the `frappe.utils.md_to_html`. 

![image](https://github.com/user-attachments/assets/9008aa8d-6380-4df8-a8b6-e2f8113cfd16)

I've added this description below the Job Description field. I hope that'll help.
