### ISSUE TITLE
[FEATURE] Breadcrumbs in Job page

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#498]
### Feature description

The job page https://fossunited.org/jobs/um3i9g5fut does not have breadcrumbs to allow a user to go back and browse the all jobs page.

**Comment by mngshm** [comment]
Understood, will add the breadcrumbs and update in the issue.

**Comment by mngshm** [comment]
https://fossunited.org/jobs/um3i9g5fut

Added breadcrumbs to the job View Page

**Comment by mngshm** [comment]
Closed this issue, since this was done.
