### ISSUE TITLE
The linters GitHub action has been failing for almost a month now

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#50]
Ref https://github.com/fossunited/fossunited/actions/workflows/linters.yml and a specific run - https://github.com/fossunited/fossunited/actions/runs/6625566335/job/17996783740 . The fixes seem straightforward and are recommended in the output of the run.

**Comment by NagariaHussain** [comment]
<img width="696" alt="CleanShot 2023-11-12 at 23 44 04@2x" src="https://github.com/fossunited/fossunited/assets/34810212/4235340f-52a0-496d-a82f-72abf128b4a9">
