### ISSUE TITLE
The custom fields don't get rendered

### ISSUE THREAD

**Issue by ad1992** [fossunited/fossunited#502]
### Describe the bug

I have  added a custom field **X / Twitter** but its not getting rendered in the CFP form

<img width="799" alt="Screenshot 2024-07-28 at 2 01 03 PM" src="https://github.com/user-attachments/assets/2252a127-c6d2-4270-8dad-4447435e1a15">

https://fossunited.org/events/2024/august/cfp

### Expected behavior

The custom field should get rendered

**Comment by rahulporuri** [comment]
thank you for reporting the bug @ad1992 . It looks like the "Type" field for the custom field isn't set and I think it's a mandatory field (even though it's not shown as mandatory). It should be a Text/Data Type if I remember correctly so could you specify "Type" and see what happens?

**Comment by mngshm** [comment]
This was not the expected workflow for adding custom fields. We'll be fixing this soon and get back to you.

**Comment by ad1992** [comment]
> thank you for reporting the bug @ad1992 . It looks like the "Type" field for the custom field isn't set and I think it's a mandatory field (even though it's not shown as mandatory). It should be a Text/Data Type if I remember correctly so could you specify "Type" and see what happens?

Yes you are right @rahulporuri , If I add the type field then it's rendered, so it would be best to show an error in case the user doesn't set the type field and also disable the update button
