### ISSUE TITLE
Deleting one of the custom fields ends up deleting all the fields

### ISSUE THREAD

**Issue by ad1992** [fossunited/fossunited#503]
### Describe the bug

When one of the fields is deleted, it deletes all the custom fields
This is an intermediate issue so not reproducible everytime, I will add a recording once I am able to reproduce again

### Expected behavior

It should only delete the selected field

**Comment by rahulporuri** [comment]
This is very alarming.

>  This is an intermediate issue so not reproducible everytime, I will add a recording once I am able to reproduce again

We will attempt to also reproduce this issue and please do report if you're able to reproduce it. Note that we've seem different behavior on Chrome vs Firefox so reproducibility might vary depending on the browser that you use.
