### ISSUE TITLE
Incorrect date in the events page

### ISSUE THREAD

**Issue by ad1992** [fossunited/fossunited#504]
### Describe the bug

The date is 24th August Saturday but its showing **25th August, Sunday** below 24th August
<img width="311" alt="Screenshot 2024-07-28 at 1 10 01 PM" src="https://github.com/user-attachments/assets/6640547c-d599-44ec-b492-89860d80b108">

https://fossunited.org/events/2024/august/

**Comment by harshtandiya** [comment]
This was fixed. 
Please note: this seems like a user error not a software error.

**Comment by ad1992** [comment]
> This was fixed. Please note: this seems like a user error not a software error.

@harshtandiya what was the error in this case ?

**Comment by harshtandiya** [comment]
It seems like the event date was not updating because the event description field was being set to empty. 

Event description is a mandatory field, that's why it must've been throwing errors on updating date from dashboard.

**Comment by ad1992** [comment]
> It seems like the event date was not updating because the event description field was being set to empty.
> 
> Event description is a mandatory field, that's why it must've been throwing errors on updating date from dashboard.

Hmm, In that case, it should be throwing errors in the UI so the users are aware of this so I would still say it is a platform error to be fixed as I don't remember seeing any error when saving.

> Event description is a mandatory field, that's why it must've been throwing errors on updating the date from the dashboard.
I don't remember seeing any errors for updating date :/
