### ISSUE TITLE
[BUG] Unable to update user profile due to incorrect username availability error

### ISSUE THREAD

**Issue by alvinsjoy** [fossunited/fossunited#505]
### Describe the bug

While attempting to update my profile details in the [dashboard](https://fossunited.org/dashboard/me), the website incorrectly flags my current username "alvin" as not available, preventing me from editing other details. However, "alvin" is already my username, and I am using it without issues. This error obstructs the profile update process.

### Expected behavior

Username must only be checked if it is being updated or username field should not display an `unavailable` error for the current username.

### To Reproduce

1. Go to the [dashboard](https://fossunited.org/dashboard/me)
2. Attempt to edit the profile details such as city, tagline, etc without changing the username.
3. Observe that the username field shows as not available.

### Screenshots

![image](https://github.com/user-attachments/assets/3190e342-ab4a-4426-9401-b61282c13a97)

### Environment

```markdown
- Device:
- OS:
- Browser:
```

**Comment by mngshm** [comment]
Hey Alvin,

I tried reproducing the error, I was not exactly able to do it the way you mentioned. But here are the things I have found while reproducing 

- I changed the username from "mangesh" to "mangesh_x0". 
- The test account of mine got swapped with my current username "mangesh", I don't know how. 
- in the admin UI, I don't have a username to my account. And in dashboard I can edit it after multiple hard reloads.

Also, thank you for reporting the issue. We'll look into it

**Comment by alvinsjoy** [comment]
Hi @Mangeshrex, thank you for investigating the issue.
Here's a video of what happens when I add `Current City` to my profile.

https://github.com/user-attachments/assets/999fc78b-4abc-4dce-81cb-8e65b55d3f16

I'm not sure why you are unable to reproduce the error.

**Comment by hafiscp** [comment]
I do have this issue on the dashboard. Hope it's getting fixed.

https://github.com/user-attachments/assets/a8acb3ba-8886-4ed6-9cbe-ff3c723a3f57

**Comment by harshtandiya** [comment]
Issue still persists.

**Comment by harshtandiya** [comment]
Weird, the PR fixed the issue for some profiles, while it exists in others. 

Can you guys text and let us know? @alvinsjoy @hafiscp

**Comment by hafiscp** [comment]
@harshtandiya Now it working smooth. Thanks for the fix.

![Screenshot 2024-08-06 at 2 20 02 PM](https://github.com/user-attachments/assets/1c72060c-53bf-441c-bb74-96a72a6ff326)
![Screenshot 2024-08-06 at 2 20 35 PM](https://github.com/user-attachments/assets/4bbe8cd9-5350-41f5-a9bb-f9e51b6dcf03)

**Comment by alvinsjoy** [comment]
> @harshtandiya Now it working smooth. Thanks for the fix.
> 
> ![Screenshot 2024-08-06 at 2 20 02 PM](https://private-user-images.githubusercontent.com/62180011/355381055-1c72060c-53bf-441c-bb74-96a72a6ff326.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTI0MzYsIm5iZiI6MTcyMjk1MjEzNiwicGF0aCI6Ii82MjE4MDAxMS8zNTUzODEwNTUtMWM3MjA2MGMtNTNiZi00NDFjLWJiNzQtOTZhNzJhNmZmMzI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEzNDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExNzAzNTlhMzJhNDhmODc4OTAyYTk1Y2M5NDYxYWJiZDU0ZmMzZmJmYmZmNWRhMmQ4MWVjMzVjNTg4ZTViODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6e9Xq6tzjRhrwciiLEZyvqoLneR6pfokL57HodK2lls) ![Screenshot 2024-08-06 at 2 20 35 PM](https://private-user-images.githubusercontent.com/62180011/355381065-4bbe8cd9-5350-41f5-a9bb-f9e51b6dcf03.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI5NTI0MzYsIm5iZiI6MTcyMjk1MjEzNiwicGF0aCI6Ii82MjE4MDAxMS8zNTUzODEwNjUtNGJiZThjZDktNTM1MC00MWY1LWE5YmItZjllNTFiNmRjZjAzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA2VDEzNDg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNjMzg4N2RkYmU2YWQ5Y2E1ZGNiODFiNTI5NmQ1OTYyY2MxM2IzNWM2Nzc3MmJlOWJlMjQ3NzIzZWRlZjU4ZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CyTVZiMzNEejKFn3MbVh09RJmHXrTfH0CtgT22qlChM)

Same for me.
Thanks.
