### ISSUE TITLE
username instead of email while adding members in the dashboard

### ISSUE THREAD

**Issue by mngshm** [fossunited/fossunited#511]
### Issue description

While adding new volunteers/chapter members the dashboard asks them to input the email of the volunteer/member. But instead the input which is supposed to be added is actually the `username` or the `full name`. 
![Capture-Jul-31-15-53-58](https://github.com/user-attachments/assets/6d1b4dde-2acd-4281-8920-7273bcc3bc8c)

![Capture-Jul-31-15-55-04](https://github.com/user-attachments/assets/27d9e035-8e01-4003-a2c9-4344a740ca62)

**Comment by harshtandiya** [comment]
closed with #535
