### ISSUE TITLE
"setup.py" file looks outdated

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#52]
For example, the author email looks like a default that frappe provides for new projects and might not be the email address that this specific project wants to use.

https://github.com/fossunited/fossunited/blob/6fbb9931875d1c9f46155aa6587642f845f73278/setup.py#L14

**Comment by NagariaHussain** [comment]
I added this email while init 😅, @harshtandiya feel free to replace. BTW setup.py + requirements.txt file has now been replaced with `pyproject.toml` file 5cbf0cc55070c6fef77eb6cc0b9c9f9920cbfac9
