### ISSUE TITLE
Flake8 is configured to ignore a large number of meaningful errors, warnings and failures

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#53]
See ignore list in https://github.com/fossunited/fossunited/blob/6fbb9931875d1c9f46155aa6587642f845f73278/.flake8

For reference, here are the references for the error codes - https://github.com/fossunited/fossunited/blob/6fbb9931875d1c9f46155aa6587642f845f73278/.flake8 and https://flake8.pycqa.org/en/latest/user/error-codes.html

**Comment by NagariaHussain** [comment]
I am thinking of replacing flake8 and black with ruff soon.

**Comment by NagariaHussain** [comment]
Done 5cbf0cc55070c6fef77eb6cc0b9c9f9920cbfac9
