### ISSUE TITLE
Add Frappeverse 2024 to events page

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#532]
### Issue description

Ref https://frappe.io/frappeverse

Maybe also mark it as must attend? 🤷

**Comment by RiyaMathew-11** [comment]
<img width="631" alt="Screenshot 2024-08-08 at 1 44 05 PM" src="https://github.com/user-attachments/assets/235a6db6-95f9-458d-a94a-2e53e475e9f1">

Added to events timeline. 

An add-on note we can add external events to events timeline. 

1. Check it as an external event. 
2. Add the event website in the URL field.
