### ISSUE TITLE
[FEATURE] List ex partners in Industry Partners page

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#533]
### Feature description

In the short time that the Foundation has been up and running, we have had a number of organizations financially support us. We should consider adding ex-industry partners to the page https://fossunited.org/industry-partners to ensure that we're still recognizing them for the support that they provided in the past.

**Comment by RiyaMathew-11** [comment]
Added the former industry partners as a separate section. : https://fossunited.org/industry-partners

Though @rahulporuri should we consider to see if the section should hold not just former industry partners but also previous flagship event sponsors too?

We could tweak the heading the mention Previous Partners and Event Sponsors - maybe?

Or add a sub-note: `Includes flagship event sponsors too.`

**Comment by rahulporuri** [comment]
> Though @rahulporuri should we consider to see if the section should hold not just former industry partners but also previous flagship event sponsors too?

Personally, I would add former event sponsors in event pages or in an entirely separate supporters page. i think we can close this issue for now.
