### ISSUE TITLE
[BUG] Wrong configuration of Ruff Formatting

### ISSUE THREAD

**Issue by mngshm** [fossunited/fossunited#537]
### Describe the bug

The ruff formatting on the platform is broken and not configured very well. Currently for linting, we only use `"I"` . Additionally, our configuration should also include rules "E" and "F".  https://docs.astral.sh/ruff/settings/#lint_select

Sharing some relevant errors from the ruff playground with the linting options "I", "E" and "F" -> https://play.ruff.rs/31a0fe0a-e3b7-427a-b35b-b4c993daa0bc. 

If E and F is removed there are 0 errors as I only deals with the formatting in the Import block of the file (If I'm not wrong). But "E" and "F" bring in errors which make the code better.

### Expected behavior

The `pyproject.toml` should include the follow options in the `[tool.ruff]` block

![Capture-Aug-08-18-17-24](https://github.com/user-attachments/assets/a9630f8c-49f3-4027-9a14-b62f89993aa5)

@rahulporuri please add a comment If I've missed anything. 

```markdown
- Device:Thinkpad t490
- OS:Arch Linux
- Browser:Firefox Nightly (v130.0.0)
```

**Comment by mngshm** [comment]
option E was added to `tool.ruff.select` in the PR #556.

**Comment by rahulporuri** [comment]
closing as the `F` option was added in #602
