### ISSUE TITLE
[Blog Post] Issue with the formating in blog posts

### ISSUE THREAD

**Issue by fossdot** [fossunited/fossunited#539]
### Issue description

I was looking for the yearly report of FOSS United which was published as a blog post on the old site - https://archive.fossunited.org/blog/report/report-22

The same post on the new site seems not to be in the right format after the 'Blog posts on IndiaFOSS 2.0' section on the page  https://fossunited.org/blog/report/report-22

![Screenshot(111)](https://github.com/user-attachments/assets/6aca9538-4f2d-4c07-adfb-b77e563643a0)

**Comment by RiyaMathew-11** [comment]
Closing this in favour of and since it included in #331
