### ISSUE TITLE
[FEATURE] Schedule pages for events (IndiaFOSS!)

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#540]
### Feature description

There is no real-time "proper" schedule page for events right now. We should work on creating something that can show the schedule of events in the platform itself.

Please discuss features that are essential/good-to-have

**Comment by rahulporuri** [comment]
it sounds like #302 is a relevant feature here.

and i've also wondered how the "schedule" page on a monthly meetup works or is meant for.

**Comment by RiyaMathew-11** [comment]
- Have all different session types cleanly rendered - Talks, Lightning Talks, Workshops, Panels.
- Each session block can have single speaker or multiple speakers
- Each session may have multiple locations: 
  - This might not be a case with a meetup
  - But for a conference:
    - For eg: IndiaFOSS talks maybe at one location and workshops in another location
- Good to have talk categories rendered too - FOSS Project showcase, Policy etc. 
- Break slots can be styled with a different shade - particularly liked it's usage in [IndiaFOSS 2023](https://indiafoss.net/2023/conference/schedule)

**Comment by RiyaMathew-11** [comment]
@harshtandiya Should we close #72 in context to the current issue. As it's pretty much the same.

Or keep it open for later? Would the schedule pages PR also have the workflow of it being set from event admin dashboard.

Also the point of reminder emails mentioned in #72 - on second thoughts wont be needed: 

1. The feat of emails from dashboard won't be up in a while. 
2. The entire schedule needn't be rendered - the event link / schedule link mentions enough would suffice I think.

cc: @rahulporuri @Mangeshrex
