### ISSUE TITLE
[BUG] Server error while signing in with google.

### ISSUE THREAD

**Issue by vishuuwu** [fossunited/fossunited#557]
### Bug description
one of our attendees faced server error while signing in with google from the link provided in the telegram community for transferring tickets. 

### Expected behavior
To be pointed to https://fossunited.org/dashboard/ticket-transfer after successful login

### Environment

```markdown
- Device: Mobile
- OS: Android
- Browser: unknown
```

### Additional context

![image](https://github.com/user-attachments/assets/8361eb39-d79f-4b56-b923-6e5159fd1d3e)

**Comment by RiyaMathew-11** [comment]
@vishuuwu  - we've fixed the issue. Would you be able to test it once and verify too ? 
Please let us know

**Comment by harshtandiya** [comment]
Tested with google account. Closing issue
