### ISSUE TITLE
FOSS Hack 2020,2021 web pages are giving 404

### ISSUE THREAD

**Issue by fossdot** [fossunited/fossunited#567]
### Issue description

FOSS Hack 2020 and 2021 web pages are giving 404. 

https://fossunited.org/fosshack/2020
https://fossunited.org/fosshack/2021

**Comment by harshtandiya** [comment]
Added redirects from `https://fossunited.org` to `https://archive.fossunited.org` for the following web pages.

**Comment by rahulporuri** [comment]
@harshtandiya  please add issues that you are working on to the GitHub project so that they will end up in the "Done" column when they are completed.
