### ISSUE TITLE
Make Reviews Public & Anonymous

### ISSUE THREAD

**Issue by harshtandiya** [fossunited/fossunited#604]
### Issue description

Right now, the reviews are only visible to the chapter members, proposal submitter and the reviewers. This can be changed to make the reviews **Public for all** and **Anonymous**

**Comment by rahulporuri** [comment]
Please note that we might want to always keep the reviews anonymous until after the event is complete -> and then, the public for all or anonymous options kick in

This is to ensure that the reviewers aren't influenced by the proposers during the review phase. After the review phase is complete, the reviewers can be made public and their reviews can also be made public, if the reviewers choose to do so
