### ISSUE TITLE
[BUG] Application link field in the job board does not accept email as url

### ISSUE THREAD

**Issue by ansharora28** [fossunited/fossunited#626]
### Describe the bug

The application link field on fossunited.org/jobs does not accept mailto:email as a valid url

### Screenshots

![image](https://github.com/user-attachments/assets/5cf9c862-9475-4c2e-9e5b-aa7d9047b39e)

**Comment by harshtandiya** [comment]
problem here is mailto: I guess, can you remove just `mailto:` and try again

**Comment by ansharora28** [comment]
the url wouldn't be valid in that case? In cases where the application requires sending an email.

Even that won't work by the way - the form requires me to write it as https://www.hello@tech4goodcommunity.com

**Comment by harshtandiya** [comment]
@ansharora28 This is an error in setting up the doctypes then. I will have a look and refactor

**Comment by harshtandiya** [comment]
This was changed from the backend. Now it doesn't mandate a "URL" with `https://`
