### ISSUE TITLE
Update grants page with new event grants

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#653]
### Issue description

https://fossunited.org/grants hasn't been updated since April 2024

**Comment by RiyaMathew-11** [comment]
I think we can move the grant applications via a form now ? We can easily change status via doctypes then, to have a record of grants in the system. 

We also don't have to manually enter data too. We can add notifications too for the requester based on Acceptance, Updates etc.,

**Comment by rahulporuri** [comment]
Thanks for adding these @wisharya . closing the issue
