### ISSUE TITLE
[Homepage] Telegram Group Related Issue

### ISSUE THREAD

**Issue by fossdot** [fossunited/fossunited#665]
### Issue description

I was trying to replace the Telegram group link with matrix space link from the home page, but It looks like the text `Join our Telegram Community` is hard-coded while the link can edited via the desk. Is there is quick fix for this. Not urgent.
![Screenshot(158)](https://github.com/user-attachments/assets/6ed8ee09-2c98-4d7e-96d4-2770fe92e56d)

**Comment by rahulporuri** [comment]
PR #662 updates the code to mention the Matrix room, while also linking to the Telegram community. I think we can close this issue.

@harshtandiya can you please review PR #662 ?
