### ISSUE TITLE
[BUG] Accessing a "private" profile raises a "Profile Not Found" error

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#666]
### Describe the bug

When attempting to view a "private" profile, the platform raises a `DoesNotExistError: Profile Not Found`. For better user experience, we should be raising a custom `Profile Not Accessible` error or something of that sort, to convey the fact that this profile is not public.

### To Reproduce

* Access https://fossunited.org/rahulsaiporuri

### Additional context

Traceback reported when opening the page

```
Traceback (most recent call last):
  File "apps/frappe/frappe/website/serve.py", line 20, in get_response
    response = renderer_instance.render()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 41, in render
    html = self.get_html()
           ^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/utils.py", line 529, in cache_html_decorator
    html = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 50, in get_html
    self.update_context()
  File "apps/frappe/frappe/website/page_renderers/document_page.py", line 65, in update_context
    ret = self.doc.get_context(self.context)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "apps/fossunited/fossunited/foss_profiles/doctype/foss_user_profile/foss_user_profile.py", line 117, in get_context
    frappe.throw("Profile Not Found", frappe.DoesNotExistError)
  File "apps/frappe/frappe/__init__.py", line 652, in throw
    msgprint(
  File "apps/frappe/frappe/__init__.py", line 617, in msgprint
    _raise_exception()
  File "apps/frappe/frappe/__init__.py", line 568, in _raise_exception
    raise exc
frappe.exceptions.DoesNotExistError: Profile Not Found
```

**Comment by vasujain275** [comment]
Hey @rahulporuri, can I work on this?

**Comment by vasujain275** [comment]
I can't reproduce this bug on my local setup, I create a user with username - test, made its profile private and then tried to access it using  - http://test.localhost:8000/test, but It showed no error in the console, here are the screenshots - 

![image](https://github.com/user-attachments/assets/91646550-6b49-4bd8-946d-fc34903a9782)
![image](https://github.com/user-attachments/assets/c5092328-a166-446b-ae42-0466e6761785)

**Comment by rahulporuri** [comment]
> I can't reproduce this bug on my local setup, I create a user with username - test, made its profile private and then tried to access it using - http://test.localhost:8000/test, but It showed no error in the console, here are the screenshots

in order to reproduce the error, you need to logout and open the profile. even if you mark your profile as private, it is expected for the profile owner to be able to open it. the problem appears when somehow the profile link is accessible to someone other than the profile owner.

does that make sense @vasujain275 ?

**Comment by vasujain275** [comment]
@rahulporuri Yes reproduced it on my local environment, can you please assign me this?

**Comment by rahulporuri** [comment]
Can you propose a solution @vasujain275 before you start working on it? It'll be better to confirm that the solution you propose makes sense for the project before implementing it.

**Comment by vasujain275** [comment]
@rahulporuri I am trying to figure it out, as I am new to the Frappe framework. I am currently reading the frappe documentation and this repository docs to gain a basic understanding of the project's architecture.

**Comment by rahulporuri** [comment]
@vasujain275 the simple solution is to

1. create a new exception class that inherits from one of the existing `frappe.exceptions`
2. raise this new exception in the below code instead of raising the `DoesNotExistError` exception
3. update the message to `"Profile is Private"` or something of that sort
4. add a test to verify that if the profile is private, the correct exception is raised and we see the expected message

https://github.com/fossunited/fossunited/blob/36a145850af0feeb2dcad05aa5613f6ecf7ca278/fossunited/foss_profiles/doctype/foss_user_profile/foss_user_profile.py#L113-L117

there could be a more complicated solution that involves a completely different page or other UI elements denoting that the profile is private but we can go with the simpler option for now

@harshtandiya does that sound like a reasonable solution for this issue?

**Comment by vasujain275** [comment]
@rahulporuri Raised a PR solving this issue.
