### ISSUE TITLE
[BUG] "All proposals" page is broken in the CFP section breadcrumbs

### ISSUE THREAD

**Issue by ansharora28** [fossunited/fossunited#668]
### Describe the bug

"All proposals" page is not accessible from the breadcrumbs on the CFP section. This is because of the redirecting url being incorrect.

### To Reproduce

Go to an event's proposals page (eg. https://fossunited.org/dashboard/cfp/chennai/oct-2024)
Click on a proposal
Click on the "All Proposals" tab 

### Screenshots

![image](https://github.com/user-attachments/assets/126fb96e-e74e-4e3e-be3f-b64768dd3929)
![image](https://github.com/user-attachments/assets/07a882ef-a314-45df-bec8-843fba3b9978)

The redirect should be to https://fossunited.org/dashboard/cfp/chennai/oct-2024 instead of https://fossunited.org/dashboard/cfp/oct-2024 (chapter name is missing in url)

**Comment by rahulporuri** [comment]
@harshtandiya can we expedite deploying this solution? unless that's already underway

**Comment by harshtandiya** [comment]
@rahulporuri deploying now
