### ISSUE TITLE
[FEATURE] Create a `/stack` page to detail FOSS project usage

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#674]
### Feature description

Ref https://zerodha.tech/stack/

* frappe framework
* bench
* mariadb
* redis
* vuejs
* python
* javascript

**Comment by rahulporuri** [comment]
I've created this - https://fossunited.org/stack - as a V0. More or less a xerox copy of the zerodha page. Happy to hear comments

**Comment by rahulporuri** [comment]
^ missing from the list are

- docker
- frappe lms
- cairosvg (dependency of mon_school)
- OSP (for live streaming)
- mention use of jitsi and element video conference somewhere
- librechat

**Comment by harshtandiya** [comment]
@rahulporuri will you be adding these or should I go ahead and do it? This should be done via desk

**Comment by rahulporuri** [comment]
> @rahulporuri will you be adding these or should I go ahead and do it? This should be done via desk

@harshtandiya please go ahead and do it. And let's also add Frappe Bench to the list + the FOSS projects we need to enable the emailing functionality from #670
