### ISSUE TITLE
[Meta] Link to branding assets on the website

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#675]
### Issue description

We should include a link to https://github.com/fossunited/Branding/ on the website. A number of orgs have a specific "media" page where they include the images, the content about the org, etc that should be used when referring to the org.

**Comment by harshtandiya** [comment]
added a link on footer
![image](https://github.com/user-attachments/assets/5b64f692-de1b-4fa4-a8f3-5c7cc5642d53)
