### ISSUE TITLE
[BUG] Broken link for redirecting to company profile on Job Board and Job View Page

### ISSUE THREAD

**Issue by vrushabhgawas14** [fossunited/fossunited#677]
### Describe the bug

Link for Redirecting to `ToolJet` and `Start Insights Private Limited` Company Profile on Job Board page is incorrect.

### To Reproduce

Go to Job Board page -> https://fossunited.org/jobs
- Click on Company Profile i.e `ToolJet` and `Start Insights Private Limited` (Before clicking on "View Details" button)
This will redirect to https://fossunited.org/Tooljet.com and https://fossunited.org/startinsights.co
Above will give "404 page not found error"

- After Clicking on **View Details** button and then clicking on Company Profile for `ToolJet` and `Start Insights Private Limited` Job post
This will redirect to https://fossunited.org/jobs/Tooljet.com and https://fossunited.org/jobs/startinsights.co
This will give "Uncaught Server Exception"

### Screenshots

![Screenshot (261)](https://github.com/user-attachments/assets/c6732f9f-1c4d-43e7-b9fc-3effcd6b97c3)
![Screenshot (260)](https://github.com/user-attachments/assets/92e9b866-acff-4e45-8ce6-92cdf4793997)

### Environment

```markdown
- Device:
- OS:
- Browser:
```

### Additional context

The Redirect should be to https://www.tooljet.com and https://www.startinsights.io

**Comment by vrushabhgawas14** [comment]
I would like to work on these if assigned.

**Comment by harshtandiya** [comment]
Hey @vrushabhgawas14 ,

Thank you for reporting this! however, i am not sure if i will be able to assign this issue to you, because jobs uses custom doctype, and it can only be changed via the admin desk. We cannot give you the access to it sadly!

This will be fixed internally, but thank you very much for reporting this!

**Comment by vrushabhgawas14** [comment]
Ok  no problem.

**Comment by rahulporuri** [comment]
@vrushabhgawas14 please pick a different issue if you are interested in contributing to the codebase! There is no dearth of issues on the platform :sweat_smile:

**Comment by harshtandiya** [comment]
This was fixed via desk. Closing this
