### ISSUE TITLE
[FEATURE] Increase logout (?) duration

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#683]
### Feature description

A few of the regular users of the platform have complained about frequently having to log-in to the platform e.g. ~ 24 hours. It will be good to look into what the logout duration is at the moment and if we can increase it e.g. to 1 week which other platforms use.

**Comment by harshtandiya** [comment]
Fixed via desk.

How to :

- Go to desk `/app` of the site
- Search for settings and select `Open Settings`
![image](https://github.com/user-attachments/assets/5db01ff0-c17c-4dab-a853-70e72e5ccb07)
- Go to `System Settings`
![image](https://github.com/user-attachments/assets/771c2e21-d244-438c-a044-0e983be96ec7)
- Go to `Login` tab
- Change the value of `Session Expiry`
![image](https://github.com/user-attachments/assets/eee146b0-022e-4f76-9c7e-a592ca2db8b0)
