### ISSUE TITLE
[BUG] "View all events" on /events page goes to a bad page

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#745]
### Describe the bug

From https://fossunited.org/events, clicking on "View all events" takes me to `https://fossunited.org/{{view_events_link }}`, which of course fails

**Comment by rahulporuri** [comment]
@harshtandiya we should fix this asap

**Comment by harshtandiya** [comment]
fixed via desk

**Comment by rahulporuri** [comment]
This also exist on https://fossunited.org/ in the "View all upcoming events" section

**Comment by rahulporuri** [comment]
but it seems to be fixed on the homepage too now.

**Comment by rahulporuri** [comment]
@harshtandiya can i ask why this bug popped up in the first place?

**Comment by harshtandiya** [comment]
That was fixed too

**Comment by harshtandiya** [comment]
@rahulporuri I deleted the template from these 2 web pages as there was a bug #725 

When I re-added after the fix, i forgot to put the links
