### ISSUE TITLE
[BUG] External events (e.g. old CityFOSS confs) don't display city chapter info in timeline

### ISSUE THREAD

**Issue by rahulporuri** [fossunited/fossunited#746]
### Describe the bug

The GoaFOSS 2023 event is listed under the Goa community - https://fossunited.org/c/goa - but on the events timeline - https://fossunited.org/events/timeline, the event card doesn't use the `Goa` city chapter info

|city page|events timeline|
|---|---|
|![Screenshot from 2024-12-26 00-25-49](https://github.com/user-attachments/assets/bdd12529-e52b-45a7-86e3-4c0564b45490)|![Screenshot from 2024-12-26 00-27-00](https://github.com/user-attachments/assets/c4e92216-cdde-43ce-8e86-d0960cecb08a)|

**Comment by harshtandiya** [comment]
It's marked as an `external_event` that's why, this needs logic change in event card template. If external event linked with a chapter, show the chapter badge
